// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID            int
	Name          string
	NotifyEnabled bool
	WebexRoomID   pgtype.Text
}

type Ticket struct {
	ID           int
	Summary      string
	BoardID      int
	OwnerID      pgtype.Int4
	Resources    pgtype.Text
	UpdatedBy    pgtype.Text
	AddedToStore pgtype.Timestamp
}

type TicketNote struct {
	ID       int
	TicketID int
	Notified bool
}
