// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Board struct {
	ID            int     `json:"id"`
	Name          string  `json:"name"`
	NotifyEnabled bool    `json:"notify_enabled"`
	WebexRoomID   *string `json:"webex_room_id"`
}

type Ticket struct {
	ID           int       `json:"id"`
	Summary      string    `json:"summary"`
	BoardID      int       `json:"board_id"`
	OwnerID      *int32    `json:"owner_id"`
	Resources    *string   `json:"resources"`
	UpdatedBy    *string   `json:"updated_by"`
	AddedToStore time.Time `json:"added_to_store"`
}

type TicketNote struct {
	ID       int     `json:"id"`
	TicketID int     `json:"ticket_id"`
	Notified bool    `json:"notified"`
	Member   *string `json:"member"`
	Contact  *string `json:"contact"`
}
