// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const deleteTicketNote = `-- name: DeleteTicketNote :exec
DELETE FROM ticket_notes
WHERE id = $1
`

func (q *Queries) DeleteTicketNote(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicketNote, id)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id, name, notify_enabled, webex_room_id FROM boards
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBoard(ctx context.Context, id int) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NotifyEnabled,
		&i.WebexRoomID,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, summary, board_id, owner_id, resources, updated_by, added_to_store FROM tickets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, id int) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.OwnerID,
		&i.Resources,
		&i.UpdatedBy,
		&i.AddedToStore,
	)
	return i, err
}

const getTicketNote = `-- name: GetTicketNote :one
SELECT id, ticket_id, notified, member, contact FROM ticket_notes
WHERE id = $1
`

func (q *Queries) GetTicketNote(ctx context.Context, id int) (TicketNote, error) {
	row := q.db.QueryRow(ctx, getTicketNote, id)
	var i TicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Notified,
		&i.Member,
		&i.Contact,
	)
	return i, err
}

const insertBoard = `-- name: InsertBoard :one
INSERT INTO boards
(id, name, notify_enabled, webex_room_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, notify_enabled, webex_room_id
`

type InsertBoardParams struct {
	ID            int     `json:"id"`
	Name          string  `json:"name"`
	NotifyEnabled bool    `json:"notify_enabled"`
	WebexRoomID   *string `json:"webex_room_id"`
}

func (q *Queries) InsertBoard(ctx context.Context, arg InsertBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, insertBoard,
		arg.ID,
		arg.Name,
		arg.NotifyEnabled,
		arg.WebexRoomID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NotifyEnabled,
		&i.WebexRoomID,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO tickets
(id, summary, board_id, owner_id, resources, updated_by, added_to_store)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, summary, board_id, owner_id, resources, updated_by, added_to_store
`

type InsertTicketParams struct {
	ID           int       `json:"id"`
	Summary      string    `json:"summary"`
	BoardID      int       `json:"board_id"`
	OwnerID      *int32    `json:"owner_id"`
	Resources    *string   `json:"resources"`
	UpdatedBy    *string   `json:"updated_by"`
	AddedToStore time.Time `json:"added_to_store"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, insertTicket,
		arg.ID,
		arg.Summary,
		arg.BoardID,
		arg.OwnerID,
		arg.Resources,
		arg.UpdatedBy,
		arg.AddedToStore,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.OwnerID,
		&i.Resources,
		&i.UpdatedBy,
		&i.AddedToStore,
	)
	return i, err
}

const insertTicketNote = `-- name: InsertTicketNote :one
INSERT INTO ticket_notes
(id, ticket_id, notified, member, contact)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, notified, member, contact
`

type InsertTicketNoteParams struct {
	ID       int     `json:"id"`
	TicketID int     `json:"ticket_id"`
	Notified bool    `json:"notified"`
	Member   *string `json:"member"`
	Contact  *string `json:"contact"`
}

func (q *Queries) InsertTicketNote(ctx context.Context, arg InsertTicketNoteParams) (TicketNote, error) {
	row := q.db.QueryRow(ctx, insertTicketNote,
		arg.ID,
		arg.TicketID,
		arg.Notified,
		arg.Member,
		arg.Contact,
	)
	var i TicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Notified,
		&i.Member,
		&i.Contact,
	)
	return i, err
}

const listAllTicketNotes = `-- name: ListAllTicketNotes :many
SELECT id, ticket_id, notified, member, contact FROM ticket_notes
ORDER BY id
`

func (q *Queries) ListAllTicketNotes(ctx context.Context) ([]TicketNote, error) {
	rows, err := q.db.Query(ctx, listAllTicketNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketNote
	for rows.Next() {
		var i TicketNote
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Notified,
			&i.Member,
			&i.Contact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT id, name, notify_enabled, webex_room_id FROM boards
ORDER BY id
`

func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NotifyEnabled,
			&i.WebexRoomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketNotesByTicket = `-- name: ListTicketNotesByTicket :many
SELECT id, ticket_id, notified, member, contact FROM ticket_notes
WHERE ticket_id = $1
ORDER BY id
`

func (q *Queries) ListTicketNotesByTicket(ctx context.Context, ticketID int) ([]TicketNote, error) {
	rows, err := q.db.Query(ctx, listTicketNotesByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketNote
	for rows.Next() {
		var i TicketNote
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Notified,
			&i.Member,
			&i.Contact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, summary, board_id, owner_id, resources, updated_by, added_to_store FROM tickets
ORDER BY id
`

func (q *Queries) ListTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Summary,
			&i.BoardID,
			&i.OwnerID,
			&i.Resources,
			&i.UpdatedBy,
			&i.AddedToStore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNoteNotified = `-- name: SetNoteNotified :one
UPDATE ticket_notes
SET
    notified = $2
WHERE id = $1
RETURNING id, ticket_id, notified, member, contact
`

type SetNoteNotifiedParams struct {
	ID       int  `json:"id"`
	Notified bool `json:"notified"`
}

func (q *Queries) SetNoteNotified(ctx context.Context, arg SetNoteNotifiedParams) (TicketNote, error) {
	row := q.db.QueryRow(ctx, setNoteNotified, arg.ID, arg.Notified)
	var i TicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Notified,
		&i.Member,
		&i.Contact,
	)
	return i, err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET
    name = $2,
    notify_enabled = $3,
    webex_room_id = $4
WHERE id = $1
RETURNING id, name, notify_enabled, webex_room_id
`

type UpdateBoardParams struct {
	ID            int     `json:"id"`
	Name          string  `json:"name"`
	NotifyEnabled bool    `json:"notify_enabled"`
	WebexRoomID   *string `json:"webex_room_id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.ID,
		arg.Name,
		arg.NotifyEnabled,
		arg.WebexRoomID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NotifyEnabled,
		&i.WebexRoomID,
	)
	return i, err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET
    summary = $2,
    board_id = $3,
    owner_id = $4,
    resources = $5,
    updated_by = $6,
    added_to_store = $7
WHERE id = $1
RETURNING id, summary, board_id, owner_id, resources, updated_by, added_to_store
`

type UpdateTicketParams struct {
	ID           int       `json:"id"`
	Summary      string    `json:"summary"`
	BoardID      int       `json:"board_id"`
	OwnerID      *int32    `json:"owner_id"`
	Resources    *string   `json:"resources"`
	UpdatedBy    *string   `json:"updated_by"`
	AddedToStore time.Time `json:"added_to_store"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Summary,
		arg.BoardID,
		arg.OwnerID,
		arg.Resources,
		arg.UpdatedBy,
		arg.AddedToStore,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.OwnerID,
		&i.Resources,
		&i.UpdatedBy,
		&i.AddedToStore,
	)
	return i, err
}

const updateTicketNote = `-- name: UpdateTicketNote :one
UPDATE ticket_notes
SET
    ticket_id = $2,
    notified = $3,
    member = $4,
    contact = $5
WHERE id = $1
RETURNING id, ticket_id, notified, member, contact
`

type UpdateTicketNoteParams struct {
	ID       int     `json:"id"`
	TicketID int     `json:"ticket_id"`
	Notified bool    `json:"notified"`
	Member   *string `json:"member"`
	Contact  *string `json:"contact"`
}

func (q *Queries) UpdateTicketNote(ctx context.Context, arg UpdateTicketNoteParams) (TicketNote, error) {
	row := q.db.QueryRow(ctx, updateTicketNote,
		arg.ID,
		arg.TicketID,
		arg.Notified,
		arg.Member,
		arg.Contact,
	)
	var i TicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Notified,
		&i.Member,
		&i.Contact,
	)
	return i, err
}
