// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_user.sql

package db

import (
	"context"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS(
    SELECT 1
    FROM api_user
    WHERE email_address = $1
) as exists
`

func (q *Queries) CheckUserExists(ctx context.Context, emailAddress string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, emailAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM api_user
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email_address, created_on, updated_on, password_hash, password_reset_required, totp_secret, totp_enabled, role, entra_oid FROM api_user
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.PasswordHash,
		&i.PasswordResetRequired,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.EntraOid,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email_address, created_on, updated_on, password_hash, password_reset_required, totp_secret, totp_enabled, role, entra_oid FROM api_user
WHERE email_address = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailAddress string) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailAddress)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.PasswordHash,
		&i.PasswordResetRequired,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.EntraOid,
	)
	return &i, err
}

const getUserByEmailFold = `-- name: GetUserByEmailFold :one
SELECT id, email_address, created_on, updated_on, password_hash, password_reset_required, totp_secret, totp_enabled, role, entra_oid FROM api_user
WHERE LOWER(email_address) = LOWER($1) LIMIT 1
`

func (q *Queries) GetUserByEmailFold(ctx context.Context, lower string) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmailFold, lower)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.PasswordHash,
		&i.PasswordResetRequired,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.EntraOid,
	)
	return &i, err
}

const getUserByEntraOID = `-- name: GetUserByEntraOID :one
SELECT id, email_address, created_on, updated_on, password_hash, password_reset_required, totp_secret, totp_enabled, role, entra_oid FROM api_user
WHERE entra_oid = $1 LIMIT 1
`

func (q *Queries) GetUserByEntraOID(ctx context.Context, entraOid *string) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, getUserByEntraOID, entraOid)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.PasswordHash,
		&i.PasswordResetRequired,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.EntraOid,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO api_user
(email_address, role)
VALUES ($1, $2)
RETURNING id, email_address, created_on, updated_on, password_hash, password_reset_required, totp_secret, totp_enabled, role, entra_oid
`

type InsertUserParams struct {
	EmailAddress string `json:"email_address"`
	Role         string `json:"role"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.EmailAddress, arg.Role)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.PasswordHash,
		&i.PasswordResetRequired,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.EntraOid,
	)
	return &i, err
}

const linkUserEntra = `-- name: LinkUserEntra :exec
UPDATE api_user
SET entra_oid = $2, email_address = $3, updated_on = NOW()
WHERE id = $1
`

type LinkUserEntraParams struct {
	ID           int     `json:"id"`
	EntraOid     *string `json:"entra_oid"`
	EmailAddress string  `json:"email_address"`
}

func (q *Queries) LinkUserEntra(ctx context.Context, arg LinkUserEntraParams) error {
	_, err := q.db.Exec(ctx, linkUserEntra, arg.ID, arg.EntraOid, arg.EmailAddress)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email_address, created_on, updated_on, password_hash, password_reset_required, totp_secret, totp_enabled, role, entra_oid FROM api_user
ORDER BY email_address
`

func (q *Queries) ListUsers(ctx context.Context) ([]*ApiUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ApiUser
	for rows.Next() {
		var i ApiUser
		if err := rows.Scan(
			&i.ID,
			&i.EmailAddress,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.PasswordHash,
			&i.PasswordResetRequired,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.Role,
			&i.EntraOid,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE api_user
SET role = $2, updated_on = NOW()
WHERE id = $1
`

type SetUserRoleParams struct {
	ID   int    `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE api_user
SET
    email_address = $2,
    updated_on = NOW()
WHERE id = $1
RETURNING id, email_address, created_on, updated_on, password_hash, password_reset_required, totp_secret, totp_enabled, role, entra_oid
`

type UpdateUserParams struct {
	ID           int    `json:"id"`
	EmailAddress string `json:"email_address"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.EmailAddress)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.PasswordHash,
		&i.PasswordResetRequired,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Role,
		&i.EntraOid,
	)
	return &i, err
}
