// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_user.sql

package db

import (
	"context"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS(
    SELECT 1
    FROM api_user
    WHERE email_address = $1
) as exists
`

func (q *Queries) CheckUserExists(ctx context.Context, emailAddress string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, emailAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM api_user
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email_address, created_on, updated_on FROM api_user
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email_address, created_on, updated_on FROM api_user
WHERE email_address = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailAddress string) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailAddress)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO api_user
(email_address)
VALUES ($1)
RETURNING id, email_address, created_on, updated_on
`

func (q *Queries) InsertUser(ctx context.Context, emailAddress string) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, insertUser, emailAddress)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email_address, created_on, updated_on FROM api_user
ORDER BY email_address
`

func (q *Queries) ListUsers(ctx context.Context) ([]*ApiUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ApiUser
	for rows.Next() {
		var i ApiUser
		if err := rows.Scan(
			&i.ID,
			&i.EmailAddress,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE api_user
SET
    deleted = true,
    updated_on = NOW()
WHERE id = $1
RETURNING id, email_address, created_on, updated_on
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE api_user
SET
    email_address = $2,
    updated_on = NOW()
WHERE id = $1
RETURNING id, email_address, created_on, updated_on
`

type UpdateUserParams struct {
	ID           int    `json:"id"`
	EmailAddress string `json:"email_address"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*ApiUser, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.EmailAddress)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}
