// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package db

import (
	"context"
)

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_key
WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, key_hash, created_on, updated_on FROM api_key
WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id int) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_key
(user_id, key_hash)
VALUES ($1, $2)
RETURNING id, user_id, key_hash, created_on, updated_on
`

type InsertAPIKeyParams struct {
	UserID  int    `json:"user_id"`
	KeyHash []byte `json:"key_hash"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey, arg.UserID, arg.KeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, key_hash, created_on, updated_on FROM api_key
ORDER BY created_on
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]*ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyHash,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAPIKey = `-- name: SoftDeleteAPIKey :one
UPDATE api_key
SET
    delete = true,
    updated_on = NOW()
WHERE id = $1
RETURNING id, user_id, key_hash, created_on, updated_on
`

func (q *Queries) SoftDeleteAPIKey(ctx context.Context, id int) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, softDeleteAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}
