// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_config.sql

package db

import (
	"context"
)

const getAppConfig = `-- name: GetAppConfig :one
SELECT id, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size, master_dry_run, cw_api_member_identifier, sso_enabled, password_login_enabled, note_preview_length, write_cap_per_ticket FROM app_config
WHERE id = 1
`

func (q *Queries) GetAppConfig(ctx context.Context) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, getAppConfig)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.RequireTotp,
		&i.DebugLogging,
		&i.LogRetentionDays,
		&i.LogCleanupIntervalHours,
		&i.LogBufferSize,
		&i.MasterDryRun,
		&i.CwApiMemberIdentifier,
		&i.SsoEnabled,
		&i.PasswordLoginEnabled,
		&i.NotePreviewLength,
		&i.WriteCapPerTicket,
	)
	return &i, err
}

const insertDefaultAppConfig = `-- name: InsertDefaultAppConfig :one
INSERT INTO app_config (id) VALUES (1)
ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
RETURNING id, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size, master_dry_run, cw_api_member_identifier, sso_enabled, password_login_enabled, note_preview_length, write_cap_per_ticket
`

func (q *Queries) InsertDefaultAppConfig(ctx context.Context) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, insertDefaultAppConfig)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.RequireTotp,
		&i.DebugLogging,
		&i.LogRetentionDays,
		&i.LogCleanupIntervalHours,
		&i.LogBufferSize,
		&i.MasterDryRun,
		&i.CwApiMemberIdentifier,
		&i.SsoEnabled,
		&i.PasswordLoginEnabled,
		&i.NotePreviewLength,
		&i.WriteCapPerTicket,
	)
	return &i, err
}

const upsertAppConfig = `-- name: UpsertAppConfig :one
INSERT INTO app_config(id, master_dry_run, cw_api_member_identifier, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size, sso_enabled, password_login_enabled, note_preview_length, write_cap_per_ticket)
VALUES(1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE SET
    master_dry_run = EXCLUDED.master_dry_run,
    cw_api_member_identifier = EXCLUDED.cw_api_member_identifier,
    max_message_length = EXCLUDED.max_message_length,
    max_concurrent_syncs = EXCLUDED.max_concurrent_syncs,
    require_totp = EXCLUDED.require_totp,
    debug_logging = EXCLUDED.debug_logging,
    log_retention_days = EXCLUDED.log_retention_days,
    log_cleanup_interval_hours = EXCLUDED.log_cleanup_interval_hours,
    log_buffer_size = EXCLUDED.log_buffer_size,
    sso_enabled = EXCLUDED.sso_enabled,
    password_login_enabled = EXCLUDED.password_login_enabled,
    note_preview_length = EXCLUDED.note_preview_length,
    write_cap_per_ticket = EXCLUDED.write_cap_per_ticket
RETURNING id, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size, master_dry_run, cw_api_member_identifier, sso_enabled, password_login_enabled, note_preview_length, write_cap_per_ticket
`

type UpsertAppConfigParams struct {
	MasterDryRun            bool   `json:"master_dry_run"`
	CwApiMemberIdentifier   string `json:"cw_api_member_identifier"`
	MaxMessageLength        int    `json:"max_message_length"`
	MaxConcurrentSyncs      int    `json:"max_concurrent_syncs"`
	RequireTotp             bool   `json:"require_totp"`
	DebugLogging            bool   `json:"debug_logging"`
	LogRetentionDays        int    `json:"log_retention_days"`
	LogCleanupIntervalHours int    `json:"log_cleanup_interval_hours"`
	LogBufferSize           int    `json:"log_buffer_size"`
	SsoEnabled              bool   `json:"sso_enabled"`
	PasswordLoginEnabled    bool   `json:"password_login_enabled"`
	NotePreviewLength       int    `json:"note_preview_length"`
	WriteCapPerTicket       int    `json:"write_cap_per_ticket"`
}

func (q *Queries) UpsertAppConfig(ctx context.Context, arg UpsertAppConfigParams) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, upsertAppConfig,
		arg.MasterDryRun,
		arg.CwApiMemberIdentifier,
		arg.MaxMessageLength,
		arg.MaxConcurrentSyncs,
		arg.RequireTotp,
		arg.DebugLogging,
		arg.LogRetentionDays,
		arg.LogCleanupIntervalHours,
		arg.LogBufferSize,
		arg.SsoEnabled,
		arg.PasswordLoginEnabled,
		arg.NotePreviewLength,
		arg.WriteCapPerTicket,
	)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.RequireTotp,
		&i.DebugLogging,
		&i.LogRetentionDays,
		&i.LogCleanupIntervalHours,
		&i.LogBufferSize,
		&i.MasterDryRun,
		&i.CwApiMemberIdentifier,
		&i.SsoEnabled,
		&i.PasswordLoginEnabled,
		&i.NotePreviewLength,
		&i.WriteCapPerTicket,
	)
	return &i, err
}
