// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_state.sql

package db

import (
	"context"
)

const getAppState = `-- name: GetAppState :one
SELECT id, syncing_tickets, syncing_webex_rooms FROM app_state
WHERE id = 1
`

func (q *Queries) GetAppState(ctx context.Context) (AppState, error) {
	row := q.db.QueryRow(ctx, getAppState)
	var i AppState
	err := row.Scan(&i.ID, &i.SyncingTickets, &i.SyncingWebexRooms)
	return i, err
}

const insertDefaultAppState = `-- name: InsertDefaultAppState :one
INSERT INTO app_state (id) VALUES (1)
ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
RETURNING id, syncing_tickets, syncing_webex_rooms
`

func (q *Queries) InsertDefaultAppState(ctx context.Context) (AppState, error) {
	row := q.db.QueryRow(ctx, insertDefaultAppState)
	var i AppState
	err := row.Scan(&i.ID, &i.SyncingTickets, &i.SyncingWebexRooms)
	return i, err
}

const upsertAppState = `-- name: UpsertAppState :one
INSERT INTO app_state(id, syncing_tickets, syncing_webex_rooms)
VALUES(1, $1, $2)
ON CONFLICT (id) DO UPDATE SET
    syncing_tickets = EXCLUDED.syncing_tickets,
    syncing_webex_rooms = EXCLUDED.syncing_webex_rooms
RETURNING id, syncing_tickets, syncing_webex_rooms
`

type UpsertAppStateParams struct {
	SyncingTickets    bool `json:"syncing_tickets"`
	SyncingWebexRooms bool `json:"syncing_webex_rooms"`
}

func (q *Queries) UpsertAppState(ctx context.Context, arg UpsertAppStateParams) (AppState, error) {
	row := q.db.QueryRow(ctx, upsertAppState, arg.SyncingTickets, arg.SyncingWebexRooms)
	var i AppState
	err := row.Scan(&i.ID, &i.SyncingTickets, &i.SyncingWebexRooms)
	return i, err
}
