// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_config.sql

package db

import (
	"context"
)

const getAppConfig = `-- name: GetAppConfig :one
SELECT id, attempt_notify, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size FROM app_config
WHERE id = 1
`

func (q *Queries) GetAppConfig(ctx context.Context) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, getAppConfig)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AttemptNotify,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.RequireTotp,
		&i.DebugLogging,
		&i.LogRetentionDays,
		&i.LogCleanupIntervalHours,
		&i.LogBufferSize,
	)
	return &i, err
}

const insertDefaultAppConfig = `-- name: InsertDefaultAppConfig :one
INSERT INTO app_config (id) VALUES (1)
ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
RETURNING id, attempt_notify, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size
`

func (q *Queries) InsertDefaultAppConfig(ctx context.Context) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, insertDefaultAppConfig)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AttemptNotify,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.RequireTotp,
		&i.DebugLogging,
		&i.LogRetentionDays,
		&i.LogCleanupIntervalHours,
		&i.LogBufferSize,
	)
	return &i, err
}

const upsertAppConfig = `-- name: UpsertAppConfig :one
INSERT INTO app_config(id, attempt_notify, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size)
VALUES(1, $1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    attempt_notify = EXCLUDED.attempt_notify,
    max_message_length = EXCLUDED.max_message_length,
    max_concurrent_syncs = EXCLUDED.max_concurrent_syncs,
    require_totp = EXCLUDED.require_totp,
    debug_logging = EXCLUDED.debug_logging,
    log_retention_days = EXCLUDED.log_retention_days,
    log_cleanup_interval_hours = EXCLUDED.log_cleanup_interval_hours,
    log_buffer_size = EXCLUDED.log_buffer_size
RETURNING id, attempt_notify, max_message_length, max_concurrent_syncs, require_totp, debug_logging, log_retention_days, log_cleanup_interval_hours, log_buffer_size
`

type UpsertAppConfigParams struct {
	AttemptNotify           bool `json:"attempt_notify"`
	MaxMessageLength        int  `json:"max_message_length"`
	MaxConcurrentSyncs      int  `json:"max_concurrent_syncs"`
	RequireTotp             bool `json:"require_totp"`
	DebugLogging            bool `json:"debug_logging"`
	LogRetentionDays        int  `json:"log_retention_days"`
	LogCleanupIntervalHours int  `json:"log_cleanup_interval_hours"`
	LogBufferSize           int  `json:"log_buffer_size"`
}

func (q *Queries) UpsertAppConfig(ctx context.Context, arg UpsertAppConfigParams) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, upsertAppConfig,
		arg.AttemptNotify,
		arg.MaxMessageLength,
		arg.MaxConcurrentSyncs,
		arg.RequireTotp,
		arg.DebugLogging,
		arg.LogRetentionDays,
		arg.LogCleanupIntervalHours,
		arg.LogBufferSize,
	)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AttemptNotify,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.RequireTotp,
		&i.DebugLogging,
		&i.LogRetentionDays,
		&i.LogCleanupIntervalHours,
		&i.LogBufferSize,
	)
	return &i, err
}
