// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_config.sql

package db

import (
	"context"
)

const getAppConfig = `-- name: GetAppConfig :one
SELECT id, attempt_notify, max_message_length, max_concurrent_syncs, skip_launch_syncs, require_totp FROM app_config
WHERE id = 1
`

func (q *Queries) GetAppConfig(ctx context.Context) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, getAppConfig)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AttemptNotify,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.SkipLaunchSyncs,
		&i.RequireTotp,
	)
	return &i, err
}

const insertDefaultAppConfig = `-- name: InsertDefaultAppConfig :one
INSERT INTO app_config (id) VALUES (1)
ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
RETURNING id, attempt_notify, max_message_length, max_concurrent_syncs, skip_launch_syncs, require_totp
`

func (q *Queries) InsertDefaultAppConfig(ctx context.Context) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, insertDefaultAppConfig)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AttemptNotify,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.SkipLaunchSyncs,
		&i.RequireTotp,
	)
	return &i, err
}

const upsertAppConfig = `-- name: UpsertAppConfig :one
INSERT INTO app_config(id, attempt_notify, max_message_length, max_concurrent_syncs, skip_launch_syncs, require_totp)
VALUES(1, $1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    attempt_notify = EXCLUDED.attempt_notify,
    max_message_length = EXCLUDED.max_message_length,
    max_concurrent_syncs = EXCLUDED.max_concurrent_syncs,
    skip_launch_syncs = EXCLUDED.skip_launch_syncs,
    require_totp = EXCLUDED.require_totp
RETURNING id, attempt_notify, max_message_length, max_concurrent_syncs, skip_launch_syncs, require_totp
`

type UpsertAppConfigParams struct {
	AttemptNotify      bool `json:"attempt_notify"`
	MaxMessageLength   int  `json:"max_message_length"`
	MaxConcurrentSyncs int  `json:"max_concurrent_syncs"`
	SkipLaunchSyncs    bool `json:"skip_launch_syncs"`
	RequireTotp        bool `json:"require_totp"`
}

func (q *Queries) UpsertAppConfig(ctx context.Context, arg UpsertAppConfigParams) (*AppConfig, error) {
	row := q.db.QueryRow(ctx, upsertAppConfig,
		arg.AttemptNotify,
		arg.MaxMessageLength,
		arg.MaxConcurrentSyncs,
		arg.SkipLaunchSyncs,
		arg.RequireTotp,
	)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AttemptNotify,
		&i.MaxMessageLength,
		&i.MaxConcurrentSyncs,
		&i.SkipLaunchSyncs,
		&i.RequireTotp,
	)
	return &i, err
}
