// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"
)

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT id, email_address, password_hash, created_on, updated_on
FROM api_user
WHERE email_address = $1 LIMIT 1
`

type GetUserForAuthRow struct {
	ID           int       `json:"id"`
	EmailAddress string    `json:"email_address"`
	PasswordHash []byte    `json:"password_hash"`
	CreatedOn    time.Time `json:"created_on"`
	UpdatedOn    time.Time `json:"updated_on"`
}

func (q *Queries) GetUserForAuth(ctx context.Context, emailAddress string) (*GetUserForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserForAuth, emailAddress)
	var i GetUserForAuthRow
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.PasswordHash,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE api_user
SET password_hash = $2, updated_on = NOW()
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           int    `json:"id"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}
