// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cw_board.sql

package db

import (
	"context"
)

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM cw_board
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id, name, updated_on, added_on, deleted FROM cw_board
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBoard(ctx context.Context, id int) (CwBoard, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i CwBoard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, name, updated_on, added_on, deleted FROM cw_board
ORDER BY id
`

func (q *Queries) ListBoards(ctx context.Context) ([]CwBoard, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CwBoard
	for rows.Next() {
		var i CwBoard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UpdatedOn,
			&i.AddedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBoard = `-- name: SoftDeleteBoard :exec
UPDATE cw_board
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteBoard(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteBoard, id)
	return err
}

const upsertBoard = `-- name: UpsertBoard :one
INSERT INTO cw_board
(id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    updated_on = NOW()
RETURNING id, name, updated_on, added_on, deleted
`

type UpsertBoardParams struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpsertBoard(ctx context.Context, arg UpsertBoardParams) (CwBoard, error) {
	row := q.db.QueryRow(ctx, upsertBoard, arg.ID, arg.Name)
	var i CwBoard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}
