// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cw_company.sql

package db

import (
	"context"
)

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM cw_company
WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, updated_on, added_on FROM cw_company
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCompany(ctx context.Context, id int) (*CwCompany, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i CwCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UpdatedOn,
		&i.AddedOn,
	)
	return &i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, updated_on, added_on FROM cw_company
ORDER BY id
`

func (q *Queries) ListCompanies(ctx context.Context) ([]*CwCompany, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwCompany
	for rows.Next() {
		var i CwCompany
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UpdatedOn,
			&i.AddedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCompany = `-- name: SoftDeleteCompany :exec
UPDATE cw_company
SET deleted = TRUE
WHERE id = $1
`

func (q *Queries) SoftDeleteCompany(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteCompany, id)
	return err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE cw_company
SET
    name = $2,
    updated_on = NOW()
WHERE id = $1
RETURNING id, name, updated_on, added_on
`

type UpdateCompanyParams struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (*CwCompany, error) {
	row := q.db.QueryRow(ctx, updateCompany, arg.ID, arg.Name)
	var i CwCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UpdatedOn,
		&i.AddedOn,
	)
	return &i, err
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO cw_company
(id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    updated_on = NOW()
RETURNING id, name, updated_on, added_on
`

type UpsertCompanyParams struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (*CwCompany, error) {
	row := q.db.QueryRow(ctx, upsertCompany, arg.ID, arg.Name)
	var i CwCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UpdatedOn,
		&i.AddedOn,
	)
	return &i, err
}
