// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cw_member.sql

package db

import (
	"context"
)

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM cw_member
WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, identifier, first_name, last_name, primary_email, updated_on, added_on FROM cw_member
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, id int) (*CwMember, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i CwMember
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.FirstName,
		&i.LastName,
		&i.PrimaryEmail,
		&i.UpdatedOn,
		&i.AddedOn,
	)
	return &i, err
}

const getMemberByIdentifier = `-- name: GetMemberByIdentifier :one
SELECT id, identifier, first_name, last_name, primary_email, updated_on, added_on FROM cw_member
WHERE identifier = $1 LIMIT 1
`

func (q *Queries) GetMemberByIdentifier(ctx context.Context, identifier string) (*CwMember, error) {
	row := q.db.QueryRow(ctx, getMemberByIdentifier, identifier)
	var i CwMember
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.FirstName,
		&i.LastName,
		&i.PrimaryEmail,
		&i.UpdatedOn,
		&i.AddedOn,
	)
	return &i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, identifier, first_name, last_name, primary_email, updated_on, added_on FROM cw_member
ORDER BY id
`

func (q *Queries) ListMembers(ctx context.Context) ([]*CwMember, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwMember
	for rows.Next() {
		var i CwMember
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.FirstName,
			&i.LastName,
			&i.PrimaryEmail,
			&i.UpdatedOn,
			&i.AddedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMember = `-- name: SoftDeleteMember :exec
UPDATE cw_member
SET deleted = TRUE
WHERE id = $1
`

func (q *Queries) SoftDeleteMember(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteMember, id)
	return err
}

const upsertMember = `-- name: UpsertMember :one
INSERT INTO cw_member
(id, identifier, first_name, last_name, primary_email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    identifier = EXCLUDED.identifier,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    primary_email = EXCLUDED.primary_email,
    updated_on = NOW()
RETURNING id, identifier, first_name, last_name, primary_email, updated_on, added_on
`

type UpsertMemberParams struct {
	ID           int    `json:"id"`
	Identifier   string `json:"identifier"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PrimaryEmail string `json:"primary_email"`
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) (*CwMember, error) {
	row := q.db.QueryRow(ctx, upsertMember,
		arg.ID,
		arg.Identifier,
		arg.FirstName,
		arg.LastName,
		arg.PrimaryEmail,
	)
	var i CwMember
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.FirstName,
		&i.LastName,
		&i.PrimaryEmail,
		&i.UpdatedOn,
		&i.AddedOn,
	)
	return &i, err
}
