// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cw_status.sql

package db

import (
	"context"
)

const deleteTicketStatus = `-- name: DeleteTicketStatus :exec
DELETE FROM cw_ticket_status
WHERE id = $1
`

func (q *Queries) DeleteTicketStatus(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicketStatus, id)
	return err
}

const getTicketStatus = `-- name: GetTicketStatus :one
SELECT id, board_id, name, default_status, display_on_board, inactive, closed, added_on, updated_on, deleted FROM cw_ticket_status
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicketStatus(ctx context.Context, id int) (*CwTicketStatus, error) {
	row := q.db.QueryRow(ctx, getTicketStatus, id)
	var i CwTicketStatus
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.DefaultStatus,
		&i.DisplayOnBoard,
		&i.Inactive,
		&i.Closed,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}

const listAllTicketStatuses = `-- name: ListAllTicketStatuses :many
SELECT id, board_id, name, default_status, display_on_board, inactive, closed, added_on, updated_on, deleted FROM cw_ticket_status
ORDER BY id
`

func (q *Queries) ListAllTicketStatuses(ctx context.Context) ([]*CwTicketStatus, error) {
	rows, err := q.db.Query(ctx, listAllTicketStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketStatus
	for rows.Next() {
		var i CwTicketStatus
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.DefaultStatus,
			&i.DisplayOnBoard,
			&i.Inactive,
			&i.Closed,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketStatusesByBoard = `-- name: ListTicketStatusesByBoard :many
SELECT id, board_id, name, default_status, display_on_board, inactive, closed, added_on, updated_on, deleted FROM cw_ticket_status
WHERE board_id = $1
ORDER BY id
`

func (q *Queries) ListTicketStatusesByBoard(ctx context.Context, boardID int) ([]*CwTicketStatus, error) {
	rows, err := q.db.Query(ctx, listTicketStatusesByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketStatus
	for rows.Next() {
		var i CwTicketStatus
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.DefaultStatus,
			&i.DisplayOnBoard,
			&i.Inactive,
			&i.Closed,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTicketStatus = `-- name: SoftDeleteTicketStatus :exec
UPDATE cw_ticket_status
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTicketStatus(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteTicketStatus, id)
	return err
}

const upsertTicketStatus = `-- name: UpsertTicketStatus :one
INSERT INTO cw_ticket_status (
    id,
    board_id,
    name,
    default_status,
    display_on_board,
    inactive,
    closed
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    board_id = EXCLUDED.board_id,
    name = EXCLUDED.name,
    default_status = EXCLUDED.default_status,
    display_on_board = EXCLUDED.display_on_board,
    inactive = EXCLUDED.inactive,
    closed = EXCLUDED.closed,
    updated_on = NOW()
RETURNING id, board_id, name, default_status, display_on_board, inactive, closed, added_on, updated_on, deleted
`

type UpsertTicketStatusParams struct {
	ID             int    `json:"id"`
	BoardID        int    `json:"board_id"`
	Name           string `json:"name"`
	DefaultStatus  bool   `json:"default_status"`
	DisplayOnBoard bool   `json:"display_on_board"`
	Inactive       bool   `json:"inactive"`
	Closed         bool   `json:"closed"`
}

func (q *Queries) UpsertTicketStatus(ctx context.Context, arg UpsertTicketStatusParams) (*CwTicketStatus, error) {
	row := q.db.QueryRow(ctx, upsertTicketStatus,
		arg.ID,
		arg.BoardID,
		arg.Name,
		arg.DefaultStatus,
		arg.DisplayOnBoard,
		arg.Inactive,
		arg.Closed,
	)
	var i CwTicketStatus
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.DefaultStatus,
		&i.DisplayOnBoard,
		&i.Inactive,
		&i.Closed,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}
