// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cw_ticket.sql

package db

import (
	"context"
	"time"
)

const checkTicketExists = `-- name: CheckTicketExists :one
SELECT EXISTS (
    SELECT 1
    FROM cw_ticket
    WHERE id = $1
) AS exists
`

func (q *Queries) CheckTicketExists(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRow(ctx, checkTicketExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countTicketsPaged = `-- name: CountTicketsPaged :one
SELECT COUNT(*)
FROM cw_ticket t
WHERE ($1::int IS NULL OR t.board_id = $1::int)
  AND ($2::int IS NULL OR t.status_id = $2::int)
  AND ($3::bool IS NULL OR t.closed_flag = $3::bool)
  AND ($4::bool IS TRUE OR t.deleted = FALSE)
  AND ($5::text IS NULL
       OR t.summary ILIKE '%' || $5::text || '%'
       OR t.id::text = $5::text)
`

type CountTicketsPagedParams struct {
	BoardID        *int    `json:"board_id"`
	StatusID       *int    `json:"status_id"`
	Closed         *bool   `json:"closed"`
	IncludeDeleted *bool   `json:"include_deleted"`
	Search         *string `json:"search"`
}

func (q *Queries) CountTicketsPaged(ctx context.Context, arg CountTicketsPagedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsPaged,
		arg.BoardID,
		arg.StatusID,
		arg.Closed,
		arg.IncludeDeleted,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM cw_ticket
WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT id, summary, board_id, status_id, owner_id, company_id, contact_id, resources, updated_by, updated_on, added_on, deleted, raw, priority_id, priority_name, type_id, type_name, subtype_id, subtype_name, item_id, item_name, closed_flag, latest_note_id FROM cw_ticket
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, id int) (*CwTicket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i CwTicket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.StatusID,
		&i.OwnerID,
		&i.CompanyID,
		&i.ContactID,
		&i.Resources,
		&i.UpdatedBy,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
		&i.Raw,
		&i.PriorityID,
		&i.PriorityName,
		&i.TypeID,
		&i.TypeName,
		&i.SubtypeID,
		&i.SubtypeName,
		&i.ItemID,
		&i.ItemName,
		&i.ClosedFlag,
		&i.LatestNoteID,
	)
	return &i, err
}

const listTickets = `-- name: ListTickets :many
SELECT id, summary, board_id, status_id, owner_id, company_id, contact_id, resources, updated_by, updated_on, added_on, deleted, raw, priority_id, priority_name, type_id, type_name, subtype_id, subtype_name, item_id, item_name, closed_flag, latest_note_id FROM cw_ticket
ORDER BY id
`

func (q *Queries) ListTickets(ctx context.Context) ([]*CwTicket, error) {
	rows, err := q.db.Query(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicket
	for rows.Next() {
		var i CwTicket
		if err := rows.Scan(
			&i.ID,
			&i.Summary,
			&i.BoardID,
			&i.StatusID,
			&i.OwnerID,
			&i.CompanyID,
			&i.ContactID,
			&i.Resources,
			&i.UpdatedBy,
			&i.UpdatedOn,
			&i.AddedOn,
			&i.Deleted,
			&i.Raw,
			&i.PriorityID,
			&i.PriorityName,
			&i.TypeID,
			&i.TypeName,
			&i.SubtypeID,
			&i.SubtypeName,
			&i.ItemID,
			&i.ItemName,
			&i.ClosedFlag,
			&i.LatestNoteID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsPaged = `-- name: ListTicketsPaged :many
SELECT
    t.id, t.summary, t.board_id, t.status_id, t.owner_id, t.company_id, t.contact_id, t.resources,
    t.updated_by, t.updated_on, t.added_on, t.deleted, t.priority_id, t.priority_name, t.type_id,
    t.type_name, t.subtype_id, t.subtype_name, t.item_id, t.item_name, t.closed_flag, t.latest_note_id,
    b.name AS board_name,
    s.name AS status_name,
    c.name AS company_name,
    m.first_name AS owner_first_name,
    m.last_name AS owner_last_name
FROM cw_ticket t
JOIN cw_board b ON b.id = t.board_id
JOIN cw_ticket_status s ON s.id = t.status_id
JOIN cw_company c ON c.id = t.company_id
LEFT JOIN cw_member m ON m.id = t.owner_id
WHERE ($1::int IS NULL OR t.board_id = $1::int)
  AND ($2::int IS NULL OR t.status_id = $2::int)
  AND ($3::bool IS NULL OR t.closed_flag = $3::bool)
  AND ($4::bool IS TRUE OR t.deleted = FALSE)
  AND ($5::text IS NULL
       OR t.summary ILIKE '%' || $5::text || '%'
       OR t.id::text = $5::text)
ORDER BY t.updated_on DESC, t.id DESC
LIMIT $7 OFFSET $6
`

type ListTicketsPagedParams struct {
	BoardID        *int    `json:"board_id"`
	StatusID       *int    `json:"status_id"`
	Closed         *bool   `json:"closed"`
	IncludeDeleted *bool   `json:"include_deleted"`
	Search         *string `json:"search"`
	Off            int32   `json:"off"`
	Lim            int32   `json:"lim"`
}

type ListTicketsPagedRow struct {
	ID             int       `json:"id"`
	Summary        string    `json:"summary"`
	BoardID        int       `json:"board_id"`
	StatusID       int       `json:"status_id"`
	OwnerID        *int      `json:"owner_id"`
	CompanyID      int       `json:"company_id"`
	ContactID      *int      `json:"contact_id"`
	Resources      *string   `json:"resources"`
	UpdatedBy      *string   `json:"updated_by"`
	UpdatedOn      time.Time `json:"updated_on"`
	AddedOn        time.Time `json:"added_on"`
	Deleted        bool      `json:"deleted"`
	PriorityID     *int      `json:"priority_id"`
	PriorityName   *string   `json:"priority_name"`
	TypeID         *int      `json:"type_id"`
	TypeName       *string   `json:"type_name"`
	SubtypeID      *int      `json:"subtype_id"`
	SubtypeName    *string   `json:"subtype_name"`
	ItemID         *int      `json:"item_id"`
	ItemName       *string   `json:"item_name"`
	ClosedFlag     bool      `json:"closed_flag"`
	LatestNoteID   *int      `json:"latest_note_id"`
	BoardName      string    `json:"board_name"`
	StatusName     string    `json:"status_name"`
	CompanyName    string    `json:"company_name"`
	OwnerFirstName *string   `json:"owner_first_name"`
	OwnerLastName  *string   `json:"owner_last_name"`
}

func (q *Queries) ListTicketsPaged(ctx context.Context, arg ListTicketsPagedParams) ([]*ListTicketsPagedRow, error) {
	rows, err := q.db.Query(ctx, listTicketsPaged,
		arg.BoardID,
		arg.StatusID,
		arg.Closed,
		arg.IncludeDeleted,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTicketsPagedRow
	for rows.Next() {
		var i ListTicketsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Summary,
			&i.BoardID,
			&i.StatusID,
			&i.OwnerID,
			&i.CompanyID,
			&i.ContactID,
			&i.Resources,
			&i.UpdatedBy,
			&i.UpdatedOn,
			&i.AddedOn,
			&i.Deleted,
			&i.PriorityID,
			&i.PriorityName,
			&i.TypeID,
			&i.TypeName,
			&i.SubtypeID,
			&i.SubtypeName,
			&i.ItemID,
			&i.ItemName,
			&i.ClosedFlag,
			&i.LatestNoteID,
			&i.BoardName,
			&i.StatusName,
			&i.CompanyName,
			&i.OwnerFirstName,
			&i.OwnerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTicket = `-- name: SoftDeleteTicket :exec
UPDATE cw_ticket
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTicket(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteTicket, id)
	return err
}

const upsertTicket = `-- name: UpsertTicket :one
INSERT INTO cw_ticket
(id, summary, board_id, status_id, owner_id, company_id, contact_id, resources, updated_by,
 priority_id, priority_name, type_id, type_name, subtype_id, subtype_name, item_id, item_name,
 closed_flag, latest_note_id, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
ON CONFLICT (id) DO UPDATE SET
    summary = EXCLUDED.summary,
    board_id = EXCLUDED.board_id,
    status_id = EXCLUDED.status_id,
    owner_id = EXCLUDED.owner_id,
    company_id = EXCLUDED.company_id,
    contact_id = EXCLUDED.contact_id,
    resources = EXCLUDED.resources,
    updated_by = EXCLUDED.updated_by,
    priority_id = EXCLUDED.priority_id,
    priority_name = EXCLUDED.priority_name,
    type_id = EXCLUDED.type_id,
    type_name = EXCLUDED.type_name,
    subtype_id = EXCLUDED.subtype_id,
    subtype_name = EXCLUDED.subtype_name,
    item_id = EXCLUDED.item_id,
    item_name = EXCLUDED.item_name,
    closed_flag = EXCLUDED.closed_flag,
    latest_note_id = EXCLUDED.latest_note_id,
    raw = EXCLUDED.raw,
    deleted = FALSE,
    updated_on = NOW()
RETURNING id, summary, board_id, status_id, owner_id, company_id, contact_id, resources, updated_by, updated_on, added_on, deleted, raw, priority_id, priority_name, type_id, type_name, subtype_id, subtype_name, item_id, item_name, closed_flag, latest_note_id
`

type UpsertTicketParams struct {
	ID           int     `json:"id"`
	Summary      string  `json:"summary"`
	BoardID      int     `json:"board_id"`
	StatusID     int     `json:"status_id"`
	OwnerID      *int    `json:"owner_id"`
	CompanyID    int     `json:"company_id"`
	ContactID    *int    `json:"contact_id"`
	Resources    *string `json:"resources"`
	UpdatedBy    *string `json:"updated_by"`
	PriorityID   *int    `json:"priority_id"`
	PriorityName *string `json:"priority_name"`
	TypeID       *int    `json:"type_id"`
	TypeName     *string `json:"type_name"`
	SubtypeID    *int    `json:"subtype_id"`
	SubtypeName  *string `json:"subtype_name"`
	ItemID       *int    `json:"item_id"`
	ItemName     *string `json:"item_name"`
	ClosedFlag   bool    `json:"closed_flag"`
	LatestNoteID *int    `json:"latest_note_id"`
	Raw          []byte  `json:"raw"`
}

func (q *Queries) UpsertTicket(ctx context.Context, arg UpsertTicketParams) (*CwTicket, error) {
	row := q.db.QueryRow(ctx, upsertTicket,
		arg.ID,
		arg.Summary,
		arg.BoardID,
		arg.StatusID,
		arg.OwnerID,
		arg.CompanyID,
		arg.ContactID,
		arg.Resources,
		arg.UpdatedBy,
		arg.PriorityID,
		arg.PriorityName,
		arg.TypeID,
		arg.TypeName,
		arg.SubtypeID,
		arg.SubtypeName,
		arg.ItemID,
		arg.ItemName,
		arg.ClosedFlag,
		arg.LatestNoteID,
		arg.Raw,
	)
	var i CwTicket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.StatusID,
		&i.OwnerID,
		&i.CompanyID,
		&i.ContactID,
		&i.Resources,
		&i.UpdatedBy,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
		&i.Raw,
		&i.PriorityID,
		&i.PriorityName,
		&i.TypeID,
		&i.TypeName,
		&i.SubtypeID,
		&i.SubtypeName,
		&i.ItemID,
		&i.ItemName,
		&i.ClosedFlag,
		&i.LatestNoteID,
	)
	return &i, err
}
