// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cw_ticket_type.sql

package db

import (
	"context"
)

const deleteTicketType = `-- name: DeleteTicketType :exec
DELETE FROM cw_ticket_type
WHERE id = $1
`

func (q *Queries) DeleteTicketType(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicketType, id)
	return err
}

const getTicketType = `-- name: GetTicketType :one
SELECT id, board_id, name, category, default_flag, inactive, added_on, updated_on, deleted FROM cw_ticket_type
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicketType(ctx context.Context, id int) (*CwTicketType, error) {
	row := q.db.QueryRow(ctx, getTicketType, id)
	var i CwTicketType
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Category,
		&i.DefaultFlag,
		&i.Inactive,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}

const listAllTicketTypes = `-- name: ListAllTicketTypes :many
SELECT id, board_id, name, category, default_flag, inactive, added_on, updated_on, deleted FROM cw_ticket_type
ORDER BY id
`

func (q *Queries) ListAllTicketTypes(ctx context.Context) ([]*CwTicketType, error) {
	rows, err := q.db.Query(ctx, listAllTicketTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketType
	for rows.Next() {
		var i CwTicketType
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Category,
			&i.DefaultFlag,
			&i.Inactive,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypesByBoard = `-- name: ListTicketTypesByBoard :many
SELECT id, board_id, name, category, default_flag, inactive, added_on, updated_on, deleted FROM cw_ticket_type
WHERE board_id = $1
ORDER BY id
`

func (q *Queries) ListTicketTypesByBoard(ctx context.Context, boardID int) ([]*CwTicketType, error) {
	rows, err := q.db.Query(ctx, listTicketTypesByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketType
	for rows.Next() {
		var i CwTicketType
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Category,
			&i.DefaultFlag,
			&i.Inactive,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTicketType = `-- name: SoftDeleteTicketType :exec
UPDATE cw_ticket_type
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTicketType(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteTicketType, id)
	return err
}

const upsertTicketType = `-- name: UpsertTicketType :one
INSERT INTO cw_ticket_type (
    id,
    board_id,
    name,
    category,
    default_flag,
    inactive
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    board_id = EXCLUDED.board_id,
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    default_flag = EXCLUDED.default_flag,
    inactive = EXCLUDED.inactive,
    updated_on = NOW()
RETURNING id, board_id, name, category, default_flag, inactive, added_on, updated_on, deleted
`

type UpsertTicketTypeParams struct {
	ID          int    `json:"id"`
	BoardID     int    `json:"board_id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	DefaultFlag bool   `json:"default_flag"`
	Inactive    bool   `json:"inactive"`
}

func (q *Queries) UpsertTicketType(ctx context.Context, arg UpsertTicketTypeParams) (*CwTicketType, error) {
	row := q.db.QueryRow(ctx, upsertTicketType,
		arg.ID,
		arg.BoardID,
		arg.Name,
		arg.Category,
		arg.DefaultFlag,
		arg.Inactive,
	)
	var i CwTicketType
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Category,
		&i.DefaultFlag,
		&i.Inactive,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}
