// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cw_ticket_subtype.sql

package db

import (
	"context"
)

const deleteTicketSubType = `-- name: DeleteTicketSubType :exec
DELETE FROM cw_ticket_subtype
WHERE id = $1
`

func (q *Queries) DeleteTicketSubType(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicketSubType, id)
	return err
}

const getTicketSubType = `-- name: GetTicketSubType :one
SELECT id, board_id, name, inactive, type_association_ids, added_on, updated_on, deleted FROM cw_ticket_subtype
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicketSubType(ctx context.Context, id int) (*CwTicketSubtype, error) {
	row := q.db.QueryRow(ctx, getTicketSubType, id)
	var i CwTicketSubtype
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Inactive,
		&i.TypeAssociationIds,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}

const listAllTicketSubTypes = `-- name: ListAllTicketSubTypes :many
SELECT id, board_id, name, inactive, type_association_ids, added_on, updated_on, deleted FROM cw_ticket_subtype
ORDER BY id
`

func (q *Queries) ListAllTicketSubTypes(ctx context.Context) ([]*CwTicketSubtype, error) {
	rows, err := q.db.Query(ctx, listAllTicketSubTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketSubtype
	for rows.Next() {
		var i CwTicketSubtype
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Inactive,
			&i.TypeAssociationIds,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketSubTypesByBoard = `-- name: ListTicketSubTypesByBoard :many
SELECT id, board_id, name, inactive, type_association_ids, added_on, updated_on, deleted FROM cw_ticket_subtype
WHERE board_id = $1
ORDER BY id
`

func (q *Queries) ListTicketSubTypesByBoard(ctx context.Context, boardID int) ([]*CwTicketSubtype, error) {
	rows, err := q.db.Query(ctx, listTicketSubTypesByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketSubtype
	for rows.Next() {
		var i CwTicketSubtype
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Inactive,
			&i.TypeAssociationIds,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTicketSubType = `-- name: SoftDeleteTicketSubType :exec
UPDATE cw_ticket_subtype
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTicketSubType(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteTicketSubType, id)
	return err
}

const upsertTicketSubType = `-- name: UpsertTicketSubType :one
INSERT INTO cw_ticket_subtype (
    id,
    board_id,
    name,
    inactive,
    type_association_ids
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    board_id = EXCLUDED.board_id,
    name = EXCLUDED.name,
    inactive = EXCLUDED.inactive,
    type_association_ids = EXCLUDED.type_association_ids,
    updated_on = NOW()
RETURNING id, board_id, name, inactive, type_association_ids, added_on, updated_on, deleted
`

type UpsertTicketSubTypeParams struct {
	ID                 int    `json:"id"`
	BoardID            int    `json:"board_id"`
	Name               string `json:"name"`
	Inactive           bool   `json:"inactive"`
	TypeAssociationIds []byte `json:"type_association_ids"`
}

func (q *Queries) UpsertTicketSubType(ctx context.Context, arg UpsertTicketSubTypeParams) (*CwTicketSubtype, error) {
	row := q.db.QueryRow(ctx, upsertTicketSubType,
		arg.ID,
		arg.BoardID,
		arg.Name,
		arg.Inactive,
		arg.TypeAssociationIds,
	)
	var i CwTicketSubtype
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Inactive,
		&i.TypeAssociationIds,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}
