// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cw_ticket_item.sql

package db

import (
	"context"
)

const deleteTicketItem = `-- name: DeleteTicketItem :exec
DELETE FROM cw_ticket_item
WHERE id = $1
`

func (q *Queries) DeleteTicketItem(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicketItem, id)
	return err
}

const getTicketItem = `-- name: GetTicketItem :one
SELECT id, board_id, name, inactive, added_on, updated_on, deleted FROM cw_ticket_item
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicketItem(ctx context.Context, id int) (*CwTicketItem, error) {
	row := q.db.QueryRow(ctx, getTicketItem, id)
	var i CwTicketItem
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Inactive,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}

const listAllTicketItems = `-- name: ListAllTicketItems :many
SELECT id, board_id, name, inactive, added_on, updated_on, deleted FROM cw_ticket_item
ORDER BY id
`

func (q *Queries) ListAllTicketItems(ctx context.Context) ([]*CwTicketItem, error) {
	rows, err := q.db.Query(ctx, listAllTicketItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketItem
	for rows.Next() {
		var i CwTicketItem
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Inactive,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketItemsByBoard = `-- name: ListTicketItemsByBoard :many
SELECT id, board_id, name, inactive, added_on, updated_on, deleted FROM cw_ticket_item
WHERE board_id = $1
ORDER BY id
`

func (q *Queries) ListTicketItemsByBoard(ctx context.Context, boardID int) ([]*CwTicketItem, error) {
	rows, err := q.db.Query(ctx, listTicketItemsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CwTicketItem
	for rows.Next() {
		var i CwTicketItem
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Inactive,
			&i.AddedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTicketItem = `-- name: SoftDeleteTicketItem :exec
UPDATE cw_ticket_item
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTicketItem(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteTicketItem, id)
	return err
}

const upsertTicketItem = `-- name: UpsertTicketItem :one
INSERT INTO cw_ticket_item (
    id,
    board_id,
    name,
    inactive
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    board_id = EXCLUDED.board_id,
    name = EXCLUDED.name,
    inactive = EXCLUDED.inactive,
    updated_on = NOW()
RETURNING id, board_id, name, inactive, added_on, updated_on, deleted
`

type UpsertTicketItemParams struct {
	ID       int    `json:"id"`
	BoardID  int    `json:"board_id"`
	Name     string `json:"name"`
	Inactive bool   `json:"inactive"`
}

func (q *Queries) UpsertTicketItem(ctx context.Context, arg UpsertTicketItemParams) (*CwTicketItem, error) {
	row := q.db.QueryRow(ctx, upsertTicketItem,
		arg.ID,
		arg.BoardID,
		arg.Name,
		arg.Inactive,
	)
	var i CwTicketItem
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Inactive,
		&i.AddedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return &i, err
}
