// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list.sql

package db

import (
	"context"
	"time"
)

const deleteList = `-- name: DeleteList :execrows
DELETE FROM list WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteList, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteListItem = `-- name: DeleteListItem :execrows
DELETE FROM list_item
WHERE list_id = $1 AND item_id = $2
`

type DeleteListItemParams struct {
	ListID int `json:"list_id"`
	ItemID int `json:"item_id"`
}

func (q *Queries) DeleteListItem(ctx context.Context, arg DeleteListItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListItem, arg.ListID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getList = `-- name: GetList :one
SELECT l.id, l.name, l.item_type, l.description, l.created_on, l.updated_on, (SELECT COUNT(*) FROM list_item li WHERE li.list_id = l.id) AS item_count
FROM list l
WHERE l.id = $1 LIMIT 1
`

type GetListRow struct {
	ID          int       `json:"id"`
	Name        string    `json:"name"`
	ItemType    string    `json:"item_type"`
	Description string    `json:"description"`
	CreatedOn   time.Time `json:"created_on"`
	UpdatedOn   time.Time `json:"updated_on"`
	ItemCount   int64     `json:"item_count"`
}

func (q *Queries) GetList(ctx context.Context, id int) (*GetListRow, error) {
	row := q.db.QueryRow(ctx, getList, id)
	var i GetListRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.Description,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.ItemCount,
	)
	return &i, err
}

const insertList = `-- name: InsertList :one
INSERT INTO list (name, item_type, description)
VALUES ($1, $2, $3)
RETURNING id, name, item_type, description, created_on, updated_on
`

type InsertListParams struct {
	Name        string `json:"name"`
	ItemType    string `json:"item_type"`
	Description string `json:"description"`
}

func (q *Queries) InsertList(ctx context.Context, arg InsertListParams) (*List, error) {
	row := q.db.QueryRow(ctx, insertList, arg.Name, arg.ItemType, arg.Description)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.Description,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const insertListItem = `-- name: InsertListItem :execrows
INSERT INTO list_item (list_id, item_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertListItemParams struct {
	ListID int `json:"list_id"`
	ItemID int `json:"item_id"`
}

func (q *Queries) InsertListItem(ctx context.Context, arg InsertListItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertListItem, arg.ListID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllListItems = `-- name: ListAllListItems :many
SELECT list_id, item_id FROM list_item
ORDER BY list_id, item_id
`

type ListAllListItemsRow struct {
	ListID int `json:"list_id"`
	ItemID int `json:"item_id"`
}

func (q *Queries) ListAllListItems(ctx context.Context) ([]*ListAllListItemsRow, error) {
	rows, err := q.db.Query(ctx, listAllListItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAllListItemsRow
	for rows.Next() {
		var i ListAllListItemsRow
		if err := rows.Scan(&i.ListID, &i.ItemID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListItems = `-- name: ListListItems :many
SELECT list_id, item_id, added_on FROM list_item
WHERE list_id = $1
ORDER BY added_on, item_id
`

func (q *Queries) ListListItems(ctx context.Context, listID int) ([]*ListItem, error) {
	rows, err := q.db.Query(ctx, listListItems, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListItem
	for rows.Next() {
		var i ListItem
		if err := rows.Scan(&i.ListID, &i.ItemID, &i.AddedOn); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLists = `-- name: ListLists :many
SELECT l.id, l.name, l.item_type, l.description, l.created_on, l.updated_on, (SELECT COUNT(*) FROM list_item li WHERE li.list_id = l.id) AS item_count
FROM list l
ORDER BY LOWER(l.name), l.id
`

type ListListsRow struct {
	ID          int       `json:"id"`
	Name        string    `json:"name"`
	ItemType    string    `json:"item_type"`
	Description string    `json:"description"`
	CreatedOn   time.Time `json:"created_on"`
	UpdatedOn   time.Time `json:"updated_on"`
	ItemCount   int64     `json:"item_count"`
}

func (q *Queries) ListLists(ctx context.Context) ([]*ListListsRow, error) {
	rows, err := q.db.Query(ctx, listLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListListsRow
	for rows.Next() {
		var i ListListsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.Description,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchList = `-- name: TouchList :exec
UPDATE list SET updated_on = NOW() WHERE id = $1
`

func (q *Queries) TouchList(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, touchList, id)
	return err
}

const updateList = `-- name: UpdateList :one
UPDATE list
SET name = $2, description = $3, updated_on = NOW()
WHERE id = $1
RETURNING id, name, item_type, description, created_on, updated_on
`

type UpdateListParams struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (*List, error) {
	row := q.db.QueryRow(ctx, updateList, arg.ID, arg.Name, arg.Description)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.Description,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}
