// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type ApiKey struct {
	ID        int       `json:"id"`
	UserID    int       `json:"user_id"`
	KeyHash   []byte    `json:"key_hash"`
	CreatedOn time.Time `json:"created_on"`
	UpdatedOn time.Time `json:"updated_on"`
}

type ApiUser struct {
	ID           int       `json:"id"`
	EmailAddress string    `json:"email_address"`
	CreatedOn    time.Time `json:"created_on"`
	UpdatedOn    time.Time `json:"updated_on"`
}

type AppConfig struct {
	ID                 int  `json:"id"`
	AttemptNotify      bool `json:"attempt_notify"`
	MaxMessageLength   int  `json:"max_message_length"`
	MaxConcurrentSyncs int  `json:"max_concurrent_syncs"`
}

type CwBoard struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
}

type CwCompany struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
}

type CwContact struct {
	ID        int       `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  *string   `json:"last_name"`
	CompanyID *int      `json:"company_id"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
}

type CwMember struct {
	ID           int       `json:"id"`
	Identifier   string    `json:"identifier"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PrimaryEmail string    `json:"primary_email"`
	UpdatedOn    time.Time `json:"updated_on"`
	AddedOn      time.Time `json:"added_on"`
}

type CwTicket struct {
	ID        int       `json:"id"`
	Summary   string    `json:"summary"`
	BoardID   int       `json:"board_id"`
	OwnerID   *int      `json:"owner_id"`
	CompanyID int       `json:"company_id"`
	ContactID *int      `json:"contact_id"`
	Resources *string   `json:"resources"`
	UpdatedBy *string   `json:"updated_by"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
}

type CwTicketNote struct {
	ID        int       `json:"id"`
	TicketID  int       `json:"ticket_id"`
	MemberID  *int      `json:"member_id"`
	ContactID *int      `json:"contact_id"`
	Content   *string   `json:"content"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
}

type NotifierForward struct {
	ID            int        `json:"id"`
	SourceID      int        `json:"source_id"`
	DestinationID int        `json:"destination_id"`
	StartDate     *time.Time `json:"start_date"`
	EndDate       *time.Time `json:"end_date"`
	Enabled       bool       `json:"enabled"`
	UserKeepsCopy bool       `json:"user_keeps_copy"`
	CreatedOn     time.Time  `json:"created_on"`
	UpdatedOn     time.Time  `json:"updated_on"`
}

type NotifierRule struct {
	ID               int       `json:"id"`
	CwBoardID        int       `json:"cw_board_id"`
	WebexRecipientID int       `json:"webex_recipient_id"`
	NotifyEnabled    bool      `json:"notify_enabled"`
	CreatedOn        time.Time `json:"created_on"`
}

type TicketNotification struct {
	ID              int       `json:"id"`
	TicketID        int       `json:"ticket_id"`
	TicketNoteID    *int      `json:"ticket_note_id"`
	RecipientID     *int      `json:"recipient_id"`
	ForwardedFromID *int      `json:"forwarded_from_id"`
	Sent            bool      `json:"sent"`
	Skipped         bool      `json:"skipped"`
	CreatedOn       time.Time `json:"created_on"`
	UpdatedOn       time.Time `json:"updated_on"`
}

type WebexRecipient struct {
	ID           int       `json:"id"`
	WebexID      string    `json:"webex_id"`
	Name         string    `json:"name"`
	Email        *string   `json:"email"`
	Type         string    `json:"type"`
	LastActivity time.Time `json:"last_activity"`
	CreatedOn    time.Time `json:"created_on"`
	UpdatedOn    time.Time `json:"updated_on"`
}
