// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ApiKey struct {
	ID        int       `json:"id"`
	UserID    int       `json:"user_id"`
	KeyHash   []byte    `json:"key_hash"`
	CreatedOn time.Time `json:"created_on"`
	UpdatedOn time.Time `json:"updated_on"`
	KeyHint   *string   `json:"key_hint"`
}

type ApiUser struct {
	ID                    int       `json:"id"`
	EmailAddress          string    `json:"email_address"`
	CreatedOn             time.Time `json:"created_on"`
	UpdatedOn             time.Time `json:"updated_on"`
	PasswordHash          []byte    `json:"password_hash"`
	PasswordResetRequired bool      `json:"password_reset_required"`
	TotpSecret            *string   `json:"totp_secret"`
	TotpEnabled           bool      `json:"totp_enabled"`
}

type AppConfig struct {
	ID                      int    `json:"id"`
	AttemptNotify           bool   `json:"attempt_notify"`
	MaxMessageLength        int    `json:"max_message_length"`
	MaxConcurrentSyncs      int    `json:"max_concurrent_syncs"`
	RequireTotp             bool   `json:"require_totp"`
	DebugLogging            bool   `json:"debug_logging"`
	LogRetentionDays        int    `json:"log_retention_days"`
	LogCleanupIntervalHours int    `json:"log_cleanup_interval_hours"`
	LogBufferSize           int    `json:"log_buffer_size"`
	AttemptWorkflow         bool   `json:"attempt_workflow"`
	CwBotMemberIdentifier   string `json:"cw_bot_member_identifier"`
	RootUrl                 string `json:"root_url"`
	CwCompanyID             string `json:"cw_company_id"`
	CwClientID              string `json:"cw_client_id"`
	CwPublicKey             string `json:"cw_public_key"`
	CwPrivateKey            string `json:"cw_private_key"`
	WebexSecret             string `json:"webex_secret"`
}

type AppLog struct {
	ID        int       `json:"id"`
	Time      time.Time `json:"time"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	Attrs     []byte    `json:"attrs"`
	CreatedAt time.Time `json:"created_at"`
}

type CwBoard struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
}

type CwCompany struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
}

type CwContact struct {
	ID        int       `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  *string   `json:"last_name"`
	CompanyID *int      `json:"company_id"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
}

type CwMember struct {
	ID           int       `json:"id"`
	Identifier   string    `json:"identifier"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PrimaryEmail string    `json:"primary_email"`
	UpdatedOn    time.Time `json:"updated_on"`
	AddedOn      time.Time `json:"added_on"`
	Deleted      bool      `json:"deleted"`
}

type CwTicket struct {
	ID        int       `json:"id"`
	Summary   string    `json:"summary"`
	BoardID   int       `json:"board_id"`
	StatusID  int       `json:"status_id"`
	OwnerID   *int      `json:"owner_id"`
	CompanyID int       `json:"company_id"`
	ContactID *int      `json:"contact_id"`
	Resources *string   `json:"resources"`
	UpdatedBy *string   `json:"updated_by"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
	TypeID    *int      `json:"type_id"`
	SubtypeID *int      `json:"subtype_id"`
	ItemID    *int      `json:"item_id"`
}

type CwTicketItem struct {
	ID        int       `json:"id"`
	BoardID   int       `json:"board_id"`
	Name      string    `json:"name"`
	Inactive  bool      `json:"inactive"`
	AddedOn   time.Time `json:"added_on"`
	UpdatedOn time.Time `json:"updated_on"`
	Deleted   bool      `json:"deleted"`
}

type CwTicketNote struct {
	ID        int       `json:"id"`
	TicketID  int       `json:"ticket_id"`
	MemberID  *int      `json:"member_id"`
	ContactID *int      `json:"contact_id"`
	Content   *string   `json:"content"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
}

type CwTicketStatus struct {
	ID             int       `json:"id"`
	BoardID        int       `json:"board_id"`
	Name           string    `json:"name"`
	DefaultStatus  bool      `json:"default_status"`
	DisplayOnBoard bool      `json:"display_on_board"`
	Inactive       bool      `json:"inactive"`
	Closed         bool      `json:"closed"`
	AddedOn        time.Time `json:"added_on"`
	UpdatedOn      time.Time `json:"updated_on"`
	Deleted        bool      `json:"deleted"`
}

type CwTicketSubtype struct {
	ID                 int       `json:"id"`
	BoardID            int       `json:"board_id"`
	Name               string    `json:"name"`
	Inactive           bool      `json:"inactive"`
	TypeAssociationIds []byte    `json:"type_association_ids"`
	AddedOn            time.Time `json:"added_on"`
	UpdatedOn          time.Time `json:"updated_on"`
	Deleted            bool      `json:"deleted"`
}

type CwTicketType struct {
	ID          int       `json:"id"`
	BoardID     int       `json:"board_id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	DefaultFlag bool      `json:"default_flag"`
	Inactive    bool      `json:"inactive"`
	AddedOn     time.Time `json:"added_on"`
	UpdatedOn   time.Time `json:"updated_on"`
	Deleted     bool      `json:"deleted"`
}

type NotifierForward struct {
	ID             int        `json:"id"`
	SourceID       int        `json:"source_id"`
	DestinationID  int        `json:"destination_id"`
	StartDate      *time.Time `json:"start_date"`
	EndDate        *time.Time `json:"end_date"`
	Enabled        bool       `json:"enabled"`
	UserKeepsCopy  bool       `json:"user_keeps_copy"`
	CreatedOn      time.Time  `json:"created_on"`
	UpdatedOn      time.Time  `json:"updated_on"`
	SimulationMode bool       `json:"simulation_mode"`
}

type NotifierRule struct {
	ID               int       `json:"id"`
	CwBoardID        int       `json:"cw_board_id"`
	WebexRecipientID int       `json:"webex_recipient_id"`
	NotifyEnabled    bool      `json:"notify_enabled"`
	CreatedOn        time.Time `json:"created_on"`
	SimulationMode   bool      `json:"simulation_mode"`
	NotifyOnUpdate   bool      `json:"notify_on_update"`
}

type Session struct {
	ID        int       `json:"id"`
	UserID    int       `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedOn time.Time `json:"created_on"`
}

type TicketJournal struct {
	TicketID      int       `json:"ticket_id"`
	Summary       string    `json:"summary"`
	BoardName     string    `json:"board_name"`
	CompanyName   string    `json:"company_name"`
	ContactName   string    `json:"contact_name"`
	StatusName    string    `json:"status_name"`
	OwnerName     string    `json:"owner_name"`
	LastTrigger   string    `json:"last_trigger"`
	LastOutcome   string    `json:"last_outcome"`
	HadError      bool      `json:"had_error"`
	FirstSeen     time.Time `json:"first_seen"`
	LastRun       time.Time `json:"last_run"`
	Runs          []byte    `json:"runs"`
	TypeName      string    `json:"type_name"`
	SubtypeName   string    `json:"subtype_name"`
	ItemName      string    `json:"item_name"`
	ResourceNames string    `json:"resource_names"`
}

type TicketNotification struct {
	ID              int       `json:"id"`
	TicketID        int       `json:"ticket_id"`
	TicketNoteID    *int      `json:"ticket_note_id"`
	RecipientID     *int      `json:"recipient_id"`
	ForwardedFromID *int      `json:"forwarded_from_id"`
	Sent            bool      `json:"sent"`
	Skipped         bool      `json:"skipped"`
	CreatedOn       time.Time `json:"created_on"`
	UpdatedOn       time.Time `json:"updated_on"`
}

type TotpPending struct {
	ID        int       `json:"id"`
	UserID    int       `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedOn time.Time `json:"created_on"`
}

type TotpRecoveryCode struct {
	ID        int       `json:"id"`
	UserID    int       `json:"user_id"`
	CodeHash  []byte    `json:"code_hash"`
	Used      bool      `json:"used"`
	CreatedOn time.Time `json:"created_on"`
}

type WebexRecipient struct {
	ID           int       `json:"id"`
	WebexID      string    `json:"webex_id"`
	Name         string    `json:"name"`
	Email        *string   `json:"email"`
	Type         string    `json:"type"`
	LastActivity time.Time `json:"last_activity"`
	CreatedOn    time.Time `json:"created_on"`
	UpdatedOn    time.Time `json:"updated_on"`
}

type Workflow struct {
	ID             int       `json:"id"`
	Name           string    `json:"name"`
	CwBoardID      int       `json:"cw_board_id"`
	OnTicketAction string    `json:"on_ticket_action"`
	Conditions     []byte    `json:"conditions"`
	Actions        []byte    `json:"actions"`
	Priority       int       `json:"priority"`
	Enabled        bool      `json:"enabled"`
	CreatedOn      time.Time `json:"created_on"`
	UpdatedOn      time.Time `json:"updated_on"`
	SimulationMode bool      `json:"simulation_mode"`
}

type WorkflowRun struct {
	TicketID    int       `json:"ticket_id"`
	WorkflowID  int       `json:"workflow_id"`
	ActionIndex int       `json:"action_index"`
	CreatedOn   time.Time `json:"created_on"`
}
