// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type ApiKey struct {
	ID        int32     `json:"id"`
	UserID    int       `json:"user_id"`
	KeyHash   []byte    `json:"key_hash"`
	CreatedOn time.Time `json:"created_on"`
	UpdatedOn time.Time `json:"updated_on"`
	Deleted   bool      `json:"deleted"`
}

type ApiUser struct {
	ID           int32     `json:"id"`
	EmailAddress string    `json:"email_address"`
	CreatedOn    time.Time `json:"created_on"`
	UpdatedOn    time.Time `json:"updated_on"`
	Deleted      bool      `json:"deleted"`
}

type CwBoard struct {
	ID            int       `json:"id"`
	Name          string    `json:"name"`
	NotifyEnabled bool      `json:"notify_enabled"`
	WebexRoomID   *string   `json:"webex_room_id"`
	UpdatedOn     time.Time `json:"updated_on"`
	AddedOn       time.Time `json:"added_on"`
	Deleted       bool      `json:"deleted"`
}

type CwCompany struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
}

type CwContact struct {
	ID        int       `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  *string   `json:"last_name"`
	CompanyID *int      `json:"company_id"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
}

type CwMember struct {
	ID           int       `json:"id"`
	Identifier   string    `json:"identifier"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PrimaryEmail string    `json:"primary_email"`
	UpdatedOn    time.Time `json:"updated_on"`
	AddedOn      time.Time `json:"added_on"`
	Deleted      bool      `json:"deleted"`
}

type CwTicket struct {
	ID        int       `json:"id"`
	Summary   string    `json:"summary"`
	BoardID   int       `json:"board_id"`
	OwnerID   *int      `json:"owner_id"`
	CompanyID int       `json:"company_id"`
	ContactID *int      `json:"contact_id"`
	Resources *string   `json:"resources"`
	UpdatedBy *string   `json:"updated_by"`
	UpdatedOn time.Time `json:"updated_on"`
	AddedOn   time.Time `json:"added_on"`
	Deleted   bool      `json:"deleted"`
}

type CwTicketNote struct {
	ID            int       `json:"id"`
	TicketID      int       `json:"ticket_id"`
	MemberID      *int      `json:"member_id"`
	ContactID     *int      `json:"contact_id"`
	Notified      bool      `json:"notified"`
	SkippedNotify bool      `json:"skipped_notify"`
	UpdatedOn     time.Time `json:"updated_on"`
	AddedOn       time.Time `json:"added_on"`
	Deleted       bool      `json:"deleted"`
}
