// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifier_connection.sql

package db

import (
	"context"
)

const deleteNotifierConnection = `-- name: DeleteNotifierConnection :exec
DELETE FROM notifier_connection
WHERE id = $1
`

func (q *Queries) DeleteNotifierConnection(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteNotifierConnection, id)
	return err
}

const getNotifierConnection = `-- name: GetNotifierConnection :one
SELECT nc.id, nc.cw_board_id, nc.webex_room_id, nc.notify_enabled, nc.created_on, cb.id, cb.name, cb.updated_on, cb.added_on, cb.deleted, wr.id, wr.webex_id, wr.name, wr.type, wr.created_on, wr.updated_on, wr.deleted
FROM notifier_connection nc
JOIN cw_board AS cb ON cb.id = nc.cw_board_id
JOIN webex_room AS wr ON wr.id = nc.webex_room_id
WHERE nc.id = $1
`

type GetNotifierConnectionRow struct {
	NotifierConnection NotifierConnection `json:"notifier_connection"`
	CwBoard            CwBoard            `json:"cw_board"`
	WebexRoom          WebexRoom          `json:"webex_room"`
}

func (q *Queries) GetNotifierConnection(ctx context.Context, id int) (GetNotifierConnectionRow, error) {
	row := q.db.QueryRow(ctx, getNotifierConnection, id)
	var i GetNotifierConnectionRow
	err := row.Scan(
		&i.NotifierConnection.ID,
		&i.NotifierConnection.CwBoardID,
		&i.NotifierConnection.WebexRoomID,
		&i.NotifierConnection.NotifyEnabled,
		&i.NotifierConnection.CreatedOn,
		&i.CwBoard.ID,
		&i.CwBoard.Name,
		&i.CwBoard.UpdatedOn,
		&i.CwBoard.AddedOn,
		&i.CwBoard.Deleted,
		&i.WebexRoom.ID,
		&i.WebexRoom.WebexID,
		&i.WebexRoom.Name,
		&i.WebexRoom.Type,
		&i.WebexRoom.CreatedOn,
		&i.WebexRoom.UpdatedOn,
		&i.WebexRoom.Deleted,
	)
	return i, err
}

const insertNotifierConnection = `-- name: InsertNotifierConnection :one
INSERT INTO notifier_connection(cw_board_id, webex_room_id, notify_enabled)
VALUES ($1, $2, $3)
RETURNING id, cw_board_id, webex_room_id, notify_enabled, created_on
`

type InsertNotifierConnectionParams struct {
	CwBoardID     int  `json:"cw_board_id"`
	WebexRoomID   int  `json:"webex_room_id"`
	NotifyEnabled bool `json:"notify_enabled"`
}

func (q *Queries) InsertNotifierConnection(ctx context.Context, arg InsertNotifierConnectionParams) (NotifierConnection, error) {
	row := q.db.QueryRow(ctx, insertNotifierConnection, arg.CwBoardID, arg.WebexRoomID, arg.NotifyEnabled)
	var i NotifierConnection
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}

const listNotifierConnections = `-- name: ListNotifierConnections :many
SELECT nc.id, nc.cw_board_id, nc.webex_room_id, nc.notify_enabled, nc.created_on, cb.id, cb.name, cb.updated_on, cb.added_on, cb.deleted, wr.id, wr.webex_id, wr.name, wr.type, wr.created_on, wr.updated_on, wr.deleted
FROM notifier_connection nc
JOIN cw_board AS cb ON cb.id = nc.cw_board_id
JOIN webex_room AS wr ON wr.id = nc.webex_room_id
`

type ListNotifierConnectionsRow struct {
	NotifierConnection NotifierConnection `json:"notifier_connection"`
	CwBoard            CwBoard            `json:"cw_board"`
	WebexRoom          WebexRoom          `json:"webex_room"`
}

func (q *Queries) ListNotifierConnections(ctx context.Context) ([]ListNotifierConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listNotifierConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotifierConnectionsRow
	for rows.Next() {
		var i ListNotifierConnectionsRow
		if err := rows.Scan(
			&i.NotifierConnection.ID,
			&i.NotifierConnection.CwBoardID,
			&i.NotifierConnection.WebexRoomID,
			&i.NotifierConnection.NotifyEnabled,
			&i.NotifierConnection.CreatedOn,
			&i.CwBoard.ID,
			&i.CwBoard.Name,
			&i.CwBoard.UpdatedOn,
			&i.CwBoard.AddedOn,
			&i.CwBoard.Deleted,
			&i.WebexRoom.ID,
			&i.WebexRoom.WebexID,
			&i.WebexRoom.Name,
			&i.WebexRoom.Type,
			&i.WebexRoom.CreatedOn,
			&i.WebexRoom.UpdatedOn,
			&i.WebexRoom.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierConnectionsByBoard = `-- name: ListNotifierConnectionsByBoard :many
SELECT nc.id, nc.cw_board_id, nc.webex_room_id, nc.notify_enabled, nc.created_on, cb.id, cb.name, cb.updated_on, cb.added_on, cb.deleted, wr.id, wr.webex_id, wr.name, wr.type, wr.created_on, wr.updated_on, wr.deleted
FROM notifier_connection nc
JOIN cw_board AS cb ON cb.id = nc.cw_board_id
JOIN webex_room AS wr ON wr.id = nc.webex_room_id
WHERE cb.id = $1
`

type ListNotifierConnectionsByBoardRow struct {
	NotifierConnection NotifierConnection `json:"notifier_connection"`
	CwBoard            CwBoard            `json:"cw_board"`
	WebexRoom          WebexRoom          `json:"webex_room"`
}

func (q *Queries) ListNotifierConnectionsByBoard(ctx context.Context, id int) ([]ListNotifierConnectionsByBoardRow, error) {
	rows, err := q.db.Query(ctx, listNotifierConnectionsByBoard, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotifierConnectionsByBoardRow
	for rows.Next() {
		var i ListNotifierConnectionsByBoardRow
		if err := rows.Scan(
			&i.NotifierConnection.ID,
			&i.NotifierConnection.CwBoardID,
			&i.NotifierConnection.WebexRoomID,
			&i.NotifierConnection.NotifyEnabled,
			&i.NotifierConnection.CreatedOn,
			&i.CwBoard.ID,
			&i.CwBoard.Name,
			&i.CwBoard.UpdatedOn,
			&i.CwBoard.AddedOn,
			&i.CwBoard.Deleted,
			&i.WebexRoom.ID,
			&i.WebexRoom.WebexID,
			&i.WebexRoom.Name,
			&i.WebexRoom.Type,
			&i.WebexRoom.CreatedOn,
			&i.WebexRoom.UpdatedOn,
			&i.WebexRoom.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierConnectionsByRoom = `-- name: ListNotifierConnectionsByRoom :many
SELECT nc.id, nc.cw_board_id, nc.webex_room_id, nc.notify_enabled, nc.created_on, cb.id, cb.name, cb.updated_on, cb.added_on, cb.deleted, wr.id, wr.webex_id, wr.name, wr.type, wr.created_on, wr.updated_on, wr.deleted
FROM notifier_connection nc
JOIN cw_board AS cb ON cb.id = nc.cw_board_id
JOIN webex_room AS wr ON wr.id = nc.webex_room_id
WHERE wr.id = $1
`

type ListNotifierConnectionsByRoomRow struct {
	NotifierConnection NotifierConnection `json:"notifier_connection"`
	CwBoard            CwBoard            `json:"cw_board"`
	WebexRoom          WebexRoom          `json:"webex_room"`
}

func (q *Queries) ListNotifierConnectionsByRoom(ctx context.Context, id int) ([]ListNotifierConnectionsByRoomRow, error) {
	rows, err := q.db.Query(ctx, listNotifierConnectionsByRoom, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotifierConnectionsByRoomRow
	for rows.Next() {
		var i ListNotifierConnectionsByRoomRow
		if err := rows.Scan(
			&i.NotifierConnection.ID,
			&i.NotifierConnection.CwBoardID,
			&i.NotifierConnection.WebexRoomID,
			&i.NotifierConnection.NotifyEnabled,
			&i.NotifierConnection.CreatedOn,
			&i.CwBoard.ID,
			&i.CwBoard.Name,
			&i.CwBoard.UpdatedOn,
			&i.CwBoard.AddedOn,
			&i.CwBoard.Deleted,
			&i.WebexRoom.ID,
			&i.WebexRoom.WebexID,
			&i.WebexRoom.Name,
			&i.WebexRoom.Type,
			&i.WebexRoom.CreatedOn,
			&i.WebexRoom.UpdatedOn,
			&i.WebexRoom.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotifierConnection = `-- name: SoftDeleteNotifierConnection :exec
UPDATE notifier_connection
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteNotifierConnection(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteNotifierConnection, id)
	return err
}

const updateNotifierConnection = `-- name: UpdateNotifierConnection :one
UPDATE notifier_connection
SET notify_enabled = $3
WHERE cw_board_id = $1 AND webex_room_id = $2
RETURNING id, cw_board_id, webex_room_id, notify_enabled, created_on
`

type UpdateNotifierConnectionParams struct {
	CwBoardID     int  `json:"cw_board_id"`
	WebexRoomID   int  `json:"webex_room_id"`
	NotifyEnabled bool `json:"notify_enabled"`
}

func (q *Queries) UpdateNotifierConnection(ctx context.Context, arg UpdateNotifierConnectionParams) (NotifierConnection, error) {
	row := q.db.QueryRow(ctx, updateNotifierConnection, arg.CwBoardID, arg.WebexRoomID, arg.NotifyEnabled)
	var i NotifierConnection
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}
