// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"
)

const checkNotificationsExistByNote = `-- name: CheckNotificationsExistByNote :one
SELECT EXISTS (
    SELECT 1
    FROM ticket_notification
    WHERE ticket_note_id = $1
) AS exists
`

func (q *Queries) CheckNotificationsExistByNote(ctx context.Context, ticketNoteID *int) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotificationsExistByNote, ticketNoteID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkNotificationsExistByTicketID = `-- name: CheckNotificationsExistByTicketID :one
SELECT EXISTS (
    SELECT 1
    FROM ticket_notification
    WHERE ticket_id = $1
) AS exists
`

func (q *Queries) CheckNotificationsExistByTicketID(ctx context.Context, ticketID int) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotificationsExistByTicketID, ticketID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteTicketNotification = `-- name: DeleteTicketNotification :exec
DELETE FROM ticket_notification
WHERE id = $1
`

func (q *Queries) DeleteTicketNotification(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicketNotification, id)
	return err
}

const getTicketNotification = `-- name: GetTicketNotification :one
SELECT id, ticket_id, ticket_note_id, webex_room_id, sent_to_email, sent, skipped, created_on, updated_on FROM ticket_notification
WHERE id = $1
`

func (q *Queries) GetTicketNotification(ctx context.Context, id int) (TicketNotification, error) {
	row := q.db.QueryRow(ctx, getTicketNotification, id)
	var i TicketNotification
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.TicketNoteID,
		&i.WebexRoomID,
		&i.SentToEmail,
		&i.Sent,
		&i.Skipped,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const insertTicketNotification = `-- name: InsertTicketNotification :one
INSERT INTO ticket_notification
(ticket_id, ticket_note_id, webex_room_id, sent_to_email, sent, skipped)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ticket_id, ticket_note_id, webex_room_id, sent_to_email, sent, skipped, created_on, updated_on
`

type InsertTicketNotificationParams struct {
	TicketID     int     `json:"ticket_id"`
	TicketNoteID *int    `json:"ticket_note_id"`
	WebexRoomID  *int    `json:"webex_room_id"`
	SentToEmail  *string `json:"sent_to_email"`
	Sent         bool    `json:"sent"`
	Skipped      bool    `json:"skipped"`
}

func (q *Queries) InsertTicketNotification(ctx context.Context, arg InsertTicketNotificationParams) (TicketNotification, error) {
	row := q.db.QueryRow(ctx, insertTicketNotification,
		arg.TicketID,
		arg.TicketNoteID,
		arg.WebexRoomID,
		arg.SentToEmail,
		arg.Sent,
		arg.Skipped,
	)
	var i TicketNotification
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.TicketNoteID,
		&i.WebexRoomID,
		&i.SentToEmail,
		&i.Sent,
		&i.Skipped,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const listTicketNotifications = `-- name: ListTicketNotifications :many
SELECT id, ticket_id, ticket_note_id, webex_room_id, sent_to_email, sent, skipped, created_on, updated_on FROM ticket_notification
ORDER BY created_on
`

func (q *Queries) ListTicketNotifications(ctx context.Context) ([]TicketNotification, error) {
	rows, err := q.db.Query(ctx, listTicketNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketNotification
	for rows.Next() {
		var i TicketNotification
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.TicketNoteID,
			&i.WebexRoomID,
			&i.SentToEmail,
			&i.Sent,
			&i.Skipped,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketNotificationsByNoteID = `-- name: ListTicketNotificationsByNoteID :many
SELECT id, ticket_id, ticket_note_id, webex_room_id, sent_to_email, sent, skipped, created_on, updated_on FROM ticket_notification
WHERE ticket_note_id = $1
`

func (q *Queries) ListTicketNotificationsByNoteID(ctx context.Context, ticketNoteID *int) ([]TicketNotification, error) {
	rows, err := q.db.Query(ctx, listTicketNotificationsByNoteID, ticketNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketNotification
	for rows.Next() {
		var i TicketNotification
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.TicketNoteID,
			&i.WebexRoomID,
			&i.SentToEmail,
			&i.Sent,
			&i.Skipped,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
