// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifier_forward.sql

package db

import (
	"context"
	"time"
)

const deleteNotifierForward = `-- name: DeleteNotifierForward :exec
DELETE FROM notifier_forward
WHERE id = $1
`

func (q *Queries) DeleteNotifierForward(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteNotifierForward, id)
	return err
}

const getNotifierForward = `-- name: GetNotifierForward :one
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotifierForward(ctx context.Context, id int) (NotifierForward, error) {
	row := q.db.QueryRow(ctx, getNotifierForward, id)
	var i NotifierForward
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.StartDate,
		&i.EndDate,
		&i.Enabled,
		&i.UserKeepsCopy,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const insertNotifierForward = `-- name: InsertNotifierForward :one
INSERT INTO notifier_forward (
    source_id, destination_id, start_date, end_date, enabled, user_keeps_copy
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on
`

type InsertNotifierForwardParams struct {
	SourceID      int        `json:"source_id"`
	DestinationID int        `json:"destination_id"`
	StartDate     *time.Time `json:"start_date"`
	EndDate       *time.Time `json:"end_date"`
	Enabled       bool       `json:"enabled"`
	UserKeepsCopy bool       `json:"user_keeps_copy"`
}

func (q *Queries) InsertNotifierForward(ctx context.Context, arg InsertNotifierForwardParams) (NotifierForward, error) {
	row := q.db.QueryRow(ctx, insertNotifierForward,
		arg.SourceID,
		arg.DestinationID,
		arg.StartDate,
		arg.EndDate,
		arg.Enabled,
		arg.UserKeepsCopy,
	)
	var i NotifierForward
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.StartDate,
		&i.EndDate,
		&i.Enabled,
		&i.UserKeepsCopy,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const listNotifierForwards = `-- name: ListNotifierForwards :many
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
ORDER BY id
`

func (q *Queries) ListNotifierForwards(ctx context.Context) ([]NotifierForward, error) {
	rows, err := q.db.Query(ctx, listNotifierForwards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierForward
	for rows.Next() {
		var i NotifierForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierForwardsBySourceRecipientID = `-- name: ListNotifierForwardsBySourceRecipientID :many
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
WHERE source_id = $1
ORDER BY id
`

func (q *Queries) ListNotifierForwardsBySourceRecipientID(ctx context.Context, sourceID int) ([]NotifierForward, error) {
	rows, err := q.db.Query(ctx, listNotifierForwardsBySourceRecipientID, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierForward
	for rows.Next() {
		var i NotifierForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
