// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifier_forward.sql

package db

import (
	"context"
	"time"
)

const checkNotifierForwardExists = `-- name: CheckNotifierForwardExists :one
SELECT EXISTS (
    SELECT 1
    FROM notifier_forward
    WHERE id = $1
) AS exists
`

func (q *Queries) CheckNotifierForwardExists(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotifierForwardExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteNotifierForward = `-- name: DeleteNotifierForward :exec
DELETE FROM notifier_forward
WHERE id = $1
`

func (q *Queries) DeleteNotifierForward(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteNotifierForward, id)
	return err
}

const getNotifierForward = `-- name: GetNotifierForward :one
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotifierForward(ctx context.Context, id int) (*NotifierForward, error) {
	row := q.db.QueryRow(ctx, getNotifierForward, id)
	var i NotifierForward
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.StartDate,
		&i.EndDate,
		&i.Enabled,
		&i.UserKeepsCopy,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const insertNotifierForward = `-- name: InsertNotifierForward :one
INSERT INTO notifier_forward (
    source_id, destination_id, start_date, end_date, enabled, user_keeps_copy
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on
`

type InsertNotifierForwardParams struct {
	SourceID      int        `json:"source_id"`
	DestinationID int        `json:"destination_id"`
	StartDate     *time.Time `json:"start_date"`
	EndDate       *time.Time `json:"end_date"`
	Enabled       bool       `json:"enabled"`
	UserKeepsCopy bool       `json:"user_keeps_copy"`
}

func (q *Queries) InsertNotifierForward(ctx context.Context, arg InsertNotifierForwardParams) (*NotifierForward, error) {
	row := q.db.QueryRow(ctx, insertNotifierForward,
		arg.SourceID,
		arg.DestinationID,
		arg.StartDate,
		arg.EndDate,
		arg.Enabled,
		arg.UserKeepsCopy,
	)
	var i NotifierForward
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.StartDate,
		&i.EndDate,
		&i.Enabled,
		&i.UserKeepsCopy,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const listActiveNotifierForwards = `-- name: ListActiveNotifierForwards :many
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
WHERE enabled = true
    AND (start_date IS NULL OR  start_date <= NOW())
    AND (end_date IS NULL OR end_date > NOW())
ORDER BY id
`

func (q *Queries) ListActiveNotifierForwards(ctx context.Context) ([]*NotifierForward, error) {
	rows, err := q.db.Query(ctx, listActiveNotifierForwards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifierForward
	for rows.Next() {
		var i NotifierForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveNotifierForwardsBySourceRecipientID = `-- name: ListActiveNotifierForwardsBySourceRecipientID :many
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
WHERE source_id = $1
    AND enabled = true
    AND (start_date IS NULL OR start_date <= NOW())
    AND (end_date IS NULL OR end_date > NOW())
ORDER BY id
`

func (q *Queries) ListActiveNotifierForwardsBySourceRecipientID(ctx context.Context, sourceID int) ([]*NotifierForward, error) {
	rows, err := q.db.Query(ctx, listActiveNotifierForwardsBySourceRecipientID, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifierForward
	for rows.Next() {
		var i NotifierForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInactiveNotifierForwards = `-- name: ListInactiveNotifierForwards :many
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
WHERE enabled = false
    OR (start_date IS NOT NULL AND start_date > NOW())
    OR (end_date IS NOT NULL AND end_date <= NOW())
ORDER BY id
`

func (q *Queries) ListInactiveNotifierForwards(ctx context.Context) ([]*NotifierForward, error) {
	rows, err := q.db.Query(ctx, listInactiveNotifierForwards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifierForward
	for rows.Next() {
		var i NotifierForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierForwards = `-- name: ListNotifierForwards :many
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
ORDER BY id
`

func (q *Queries) ListNotifierForwards(ctx context.Context) ([]*NotifierForward, error) {
	rows, err := q.db.Query(ctx, listNotifierForwards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifierForward
	for rows.Next() {
		var i NotifierForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierForwardsBySourceRecipientID = `-- name: ListNotifierForwardsBySourceRecipientID :many
SELECT id, source_id, destination_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM notifier_forward
WHERE source_id = $1
ORDER BY id
`

func (q *Queries) ListNotifierForwardsBySourceRecipientID(ctx context.Context, sourceID int) ([]*NotifierForward, error) {
	rows, err := q.db.Query(ctx, listNotifierForwardsBySourceRecipientID, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotifierForward
	for rows.Next() {
		var i NotifierForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierForwardsFull = `-- name: ListNotifierForwardsFull :many
SELECT 
    f.id AS id,
    f.enabled AS enabled,
    f.user_keeps_copy AS user_keeps_copy,
    f.start_date AS start_date,
    f.end_date AS end_date,
    src.id AS source_id,
    src.name AS source_name,
    src.type AS source_type,
    dst.id AS destination_id,
    dst.name AS destination_name,
    dst.type AS destination_type
FROM notifier_forward AS f
JOIN webex_recipient AS src
ON src.id = f.source_id
JOIN webex_recipient AS dst
ON dst.id = f.destination_id
`

type ListNotifierForwardsFullRow struct {
	ID              int        `json:"id"`
	Enabled         bool       `json:"enabled"`
	UserKeepsCopy   bool       `json:"user_keeps_copy"`
	StartDate       *time.Time `json:"start_date"`
	EndDate         *time.Time `json:"end_date"`
	SourceID        int        `json:"source_id"`
	SourceName      string     `json:"source_name"`
	SourceType      string     `json:"source_type"`
	DestinationID   int        `json:"destination_id"`
	DestinationName string     `json:"destination_name"`
	DestinationType string     `json:"destination_type"`
}

func (q *Queries) ListNotifierForwardsFull(ctx context.Context) ([]*ListNotifierForwardsFullRow, error) {
	rows, err := q.db.Query(ctx, listNotifierForwardsFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListNotifierForwardsFullRow
	for rows.Next() {
		var i ListNotifierForwardsFullRow
		if err := rows.Scan(
			&i.ID,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.StartDate,
			&i.EndDate,
			&i.SourceID,
			&i.SourceName,
			&i.SourceType,
			&i.DestinationID,
			&i.DestinationName,
			&i.DestinationType,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
