// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifier_connection.sql

package db

import (
	"context"
)

const checkNotifierExists = `-- name: CheckNotifierExists :one
SELECT EXISTS (
    SELECT 1
    FROM notifier_rule
    WHERE cw_board_id = $1 AND webex_room_id = $2
) AS exists
`

type CheckNotifierExistsParams struct {
	CwBoardID   int `json:"cw_board_id"`
	WebexRoomID int `json:"webex_room_id"`
}

func (q *Queries) CheckNotifierExists(ctx context.Context, arg CheckNotifierExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotifierExists, arg.CwBoardID, arg.WebexRoomID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteNotifierRule = `-- name: DeleteNotifierRule :exec
DELETE FROM notifier_rule
WHERE id = $1
`

func (q *Queries) DeleteNotifierRule(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteNotifierRule, id)
	return err
}

const getNotifierRule = `-- name: GetNotifierRule :one
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_rule
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotifierRule(ctx context.Context, id int) (NotifierRule, error) {
	row := q.db.QueryRow(ctx, getNotifierRule, id)
	var i NotifierRule
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}

const insertNotifierRule = `-- name: InsertNotifierRule :one
INSERT INTO notifier_rule(cw_board_id, webex_room_id, notify_enabled)
VALUES ($1, $2, $3)
RETURNING id, cw_board_id, webex_room_id, notify_enabled, created_on
`

type InsertNotifierRuleParams struct {
	CwBoardID     int  `json:"cw_board_id"`
	WebexRoomID   int  `json:"webex_room_id"`
	NotifyEnabled bool `json:"notify_enabled"`
}

func (q *Queries) InsertNotifierRule(ctx context.Context, arg InsertNotifierRuleParams) (NotifierRule, error) {
	row := q.db.QueryRow(ctx, insertNotifierRule, arg.CwBoardID, arg.WebexRoomID, arg.NotifyEnabled)
	var i NotifierRule
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}

const listNotifierRules = `-- name: ListNotifierRules :many
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_rule
ORDER BY id
`

func (q *Queries) ListNotifierRules(ctx context.Context) ([]NotifierRule, error) {
	rows, err := q.db.Query(ctx, listNotifierRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierRule
	for rows.Next() {
		var i NotifierRule
		if err := rows.Scan(
			&i.ID,
			&i.CwBoardID,
			&i.WebexRoomID,
			&i.NotifyEnabled,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierRulesByBoard = `-- name: ListNotifierRulesByBoard :many
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_rule
WHERE cw_board_id = $1
ORDER BY id
`

func (q *Queries) ListNotifierRulesByBoard(ctx context.Context, cwBoardID int) ([]NotifierRule, error) {
	rows, err := q.db.Query(ctx, listNotifierRulesByBoard, cwBoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierRule
	for rows.Next() {
		var i NotifierRule
		if err := rows.Scan(
			&i.ID,
			&i.CwBoardID,
			&i.WebexRoomID,
			&i.NotifyEnabled,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierRulesByRoom = `-- name: ListNotifierRulesByRoom :many
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_rule
WHERE webex_room_id = $1
ORDER BY id
`

func (q *Queries) ListNotifierRulesByRoom(ctx context.Context, webexRoomID int) ([]NotifierRule, error) {
	rows, err := q.db.Query(ctx, listNotifierRulesByRoom, webexRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierRule
	for rows.Next() {
		var i NotifierRule
		if err := rows.Scan(
			&i.ID,
			&i.CwBoardID,
			&i.WebexRoomID,
			&i.NotifyEnabled,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotifierRule = `-- name: SoftDeleteNotifierRule :exec
UPDATE notifier_rule
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteNotifierRule(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteNotifierRule, id)
	return err
}

const updateNotifierRule = `-- name: UpdateNotifierRule :one
UPDATE notifier_rule
SET
    cw_board_id = $2,
    webex_room_id = $3,
    notify_enabled = $4
WHERE id = $1
RETURNING id, cw_board_id, webex_room_id, notify_enabled, created_on
`

type UpdateNotifierRuleParams struct {
	ID            int  `json:"id"`
	CwBoardID     int  `json:"cw_board_id"`
	WebexRoomID   int  `json:"webex_room_id"`
	NotifyEnabled bool `json:"notify_enabled"`
}

func (q *Queries) UpdateNotifierRule(ctx context.Context, arg UpdateNotifierRuleParams) (NotifierRule, error) {
	row := q.db.QueryRow(ctx, updateNotifierRule,
		arg.ID,
		arg.CwBoardID,
		arg.WebexRoomID,
		arg.NotifyEnabled,
	)
	var i NotifierRule
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}
