// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"
	"time"
)

const clearOAuthClientExpiry = `-- name: ClearOAuthClientExpiry :exec
UPDATE oauth_client SET expires_at = NULL WHERE id = $1
`

func (q *Queries) ClearOAuthClientExpiry(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearOAuthClientExpiry, id)
	return err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_client (id, name, redirect_uris, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, redirect_uris, created_on, expires_at
`

type CreateOAuthClientParams struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	RedirectUris []string   `json:"redirect_uris"`
	ExpiresAt    *time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (*OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ID,
		arg.Name,
		arg.RedirectUris,
		arg.ExpiresAt,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedOn,
		&i.ExpiresAt,
	)
	return &i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec
INSERT INTO oauth_code (code_hash, grant_id, redirect_uri, code_challenge, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOAuthCodeParams struct {
	CodeHash      []byte    `json:"code_hash"`
	GrantID       int       `json:"grant_id"`
	RedirectUri   string    `json:"redirect_uri"`
	CodeChallenge string    `json:"code_challenge"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthCode,
		arg.CodeHash,
		arg.GrantID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthToken = `-- name: CreateOAuthToken :one
INSERT INTO oauth_token (grant_id, kind, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, grant_id, kind, token_hash, expires_at, created_on, used_at
`

type CreateOAuthTokenParams struct {
	GrantID   int       `json:"grant_id"`
	Kind      string    `json:"kind"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (*OauthToken, error) {
	row := q.db.QueryRow(ctx, createOAuthToken,
		arg.GrantID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedOn,
		&i.UsedAt,
	)
	return &i, err
}

const deleteExpiredOAuthClients = `-- name: DeleteExpiredOAuthClients :execrows
DELETE FROM oauth_client WHERE expires_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredOAuthClients(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthClients, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOAuthCodes = `-- name: DeleteExpiredOAuthCodes :execrows
DELETE FROM oauth_code WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredOAuthCodes(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOAuthTokens = `-- name: DeleteExpiredOAuthTokens :execrows
DELETE FROM oauth_token WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredOAuthTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOAuthGrant = `-- name: DeleteOAuthGrant :execrows
DELETE FROM oauth_grant WHERE id = $1
`

func (q *Queries) DeleteOAuthGrant(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthGrant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, name, redirect_uris, created_on, expires_at FROM oauth_client WHERE id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (*OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedOn,
		&i.ExpiresAt,
	)
	return &i, err
}

const getOAuthGrant = `-- name: GetOAuthGrant :one
SELECT id, user_id, client_id, scopes, created_on, last_used_at FROM oauth_grant WHERE id = $1
`

func (q *Queries) GetOAuthGrant(ctx context.Context, id int) (*OauthGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthGrant, id)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedOn,
		&i.LastUsedAt,
	)
	return &i, err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, grant_id, kind, token_hash, expires_at, created_on, used_at FROM oauth_token WHERE token_hash = $1
`

func (q *Queries) GetOAuthToken(ctx context.Context, tokenHash []byte) (*OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthToken, tokenHash)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedOn,
		&i.UsedAt,
	)
	return &i, err
}

const listOAuthGrantsByUser = `-- name: ListOAuthGrantsByUser :many
SELECT g.id, g.user_id, g.client_id, g.scopes, g.created_on, g.last_used_at, c.name AS client_name
FROM oauth_grant g
JOIN oauth_client c ON c.id = g.client_id
WHERE g.user_id = $1
ORDER BY g.created_on DESC
`

type ListOAuthGrantsByUserRow struct {
	ID         int        `json:"id"`
	UserID     int        `json:"user_id"`
	ClientID   string     `json:"client_id"`
	Scopes     []string   `json:"scopes"`
	CreatedOn  time.Time  `json:"created_on"`
	LastUsedAt *time.Time `json:"last_used_at"`
	ClientName string     `json:"client_name"`
}

func (q *Queries) ListOAuthGrantsByUser(ctx context.Context, userID int) ([]*ListOAuthGrantsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOAuthGrantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListOAuthGrantsByUserRow
	for rows.Next() {
		var i ListOAuthGrantsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.Scopes,
			&i.CreatedOn,
			&i.LastUsedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOAuthTokenUsed = `-- name: MarkOAuthTokenUsed :exec
UPDATE oauth_token SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOAuthTokenUsed(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, markOAuthTokenUsed, id)
	return err
}

const resolveOAuthAccessToken = `-- name: ResolveOAuthAccessToken :one
SELECT t.grant_id, t.expires_at, g.user_id, g.scopes
FROM oauth_token t
JOIN oauth_grant g ON g.id = t.grant_id
WHERE t.token_hash = $1 AND t.kind = 'access'
`

type ResolveOAuthAccessTokenRow struct {
	GrantID   int       `json:"grant_id"`
	ExpiresAt time.Time `json:"expires_at"`
	UserID    int       `json:"user_id"`
	Scopes    []string  `json:"scopes"`
}

func (q *Queries) ResolveOAuthAccessToken(ctx context.Context, tokenHash []byte) (*ResolveOAuthAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, resolveOAuthAccessToken, tokenHash)
	var i ResolveOAuthAccessTokenRow
	err := row.Scan(
		&i.GrantID,
		&i.ExpiresAt,
		&i.UserID,
		&i.Scopes,
	)
	return &i, err
}

const takeOAuthCode = `-- name: TakeOAuthCode :one
DELETE FROM oauth_code WHERE code_hash = $1
RETURNING code_hash, grant_id, redirect_uri, code_challenge, expires_at
`

func (q *Queries) TakeOAuthCode(ctx context.Context, codeHash []byte) (*OauthCode, error) {
	row := q.db.QueryRow(ctx, takeOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.GrantID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ExpiresAt,
	)
	return &i, err
}

const touchOAuthGrant = `-- name: TouchOAuthGrant :exec
UPDATE oauth_grant SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchOAuthGrant(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, touchOAuthGrant, id)
	return err
}

const upsertOAuthGrant = `-- name: UpsertOAuthGrant :one
INSERT INTO oauth_grant (user_id, client_id, scopes)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, client_id) DO UPDATE SET scopes = EXCLUDED.scopes
RETURNING id, user_id, client_id, scopes, created_on, last_used_at
`

type UpsertOAuthGrantParams struct {
	UserID   int      `json:"user_id"`
	ClientID string   `json:"client_id"`
	Scopes   []string `json:"scopes"`
}

func (q *Queries) UpsertOAuthGrant(ctx context.Context, arg UpsertOAuthGrantParams) (*OauthGrant, error) {
	row := q.db.QueryRow(ctx, upsertOAuthGrant, arg.UserID, arg.ClientID, arg.Scopes)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedOn,
		&i.LastUsedAt,
	)
	return &i, err
}
