// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_job.sql

package db

import (
	"context"
	"time"
)

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT name, last_started_at, last_finished_at, last_error FROM scheduled_job WHERE name = $1
`

func (q *Queries) GetScheduledJob(ctx context.Context, name string) (*ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getScheduledJob, name)
	var i ScheduledJob
	err := row.Scan(
		&i.Name,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.LastError,
	)
	return &i, err
}

const saveScheduledJob = `-- name: SaveScheduledJob :one
INSERT INTO scheduled_job (name, last_started_at, last_finished_at, last_error)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    last_started_at = EXCLUDED.last_started_at,
    last_finished_at = EXCLUDED.last_finished_at,
    last_error = EXCLUDED.last_error
RETURNING name, last_started_at, last_finished_at, last_error
`

type SaveScheduledJobParams struct {
	Name           string     `json:"name"`
	LastStartedAt  *time.Time `json:"last_started_at"`
	LastFinishedAt *time.Time `json:"last_finished_at"`
	LastError      *string    `json:"last_error"`
}

func (q *Queries) SaveScheduledJob(ctx context.Context, arg SaveScheduledJobParams) (*ScheduledJob, error) {
	row := q.db.QueryRow(ctx, saveScheduledJob,
		arg.Name,
		arg.LastStartedAt,
		arg.LastFinishedAt,
		arg.LastError,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.Name,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.LastError,
	)
	return &i, err
}
