// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_flow_state.sql

package db

import (
	"context"
	"time"
)

const deleteExpiredSSOFlowStates = `-- name: DeleteExpiredSSOFlowStates :exec
DELETE FROM sso_flow_state WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSSOFlowStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSSOFlowStates)
	return err
}

const putSSOFlowState = `-- name: PutSSOFlowState :exec
INSERT INTO sso_flow_state (key, state, nonce, verifier, next, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (key) DO UPDATE SET
    state = EXCLUDED.state,
    nonce = EXCLUDED.nonce,
    verifier = EXCLUDED.verifier,
    next = EXCLUDED.next,
    expires_at = EXCLUDED.expires_at
`

type PutSSOFlowStateParams struct {
	Key       string    `json:"key"`
	State     string    `json:"state"`
	Nonce     string    `json:"nonce"`
	Verifier  string    `json:"verifier"`
	Next      string    `json:"next"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) PutSSOFlowState(ctx context.Context, arg PutSSOFlowStateParams) error {
	_, err := q.db.Exec(ctx, putSSOFlowState,
		arg.Key,
		arg.State,
		arg.Nonce,
		arg.Verifier,
		arg.Next,
		arg.ExpiresAt,
	)
	return err
}

const takeSSOFlowState = `-- name: TakeSSOFlowState :one
DELETE FROM sso_flow_state
WHERE key = $1
RETURNING key, state, nonce, verifier, next, expires_at
`

func (q *Queries) TakeSSOFlowState(ctx context.Context, key string) (*SsoFlowState, error) {
	row := q.db.QueryRow(ctx, takeSSOFlowState, key)
	var i SsoFlowState
	err := row.Scan(
		&i.Key,
		&i.State,
		&i.Nonce,
		&i.Verifier,
		&i.Next,
		&i.ExpiresAt,
	)
	return &i, err
}
