// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_role_mapping.sql

package db

import (
	"context"
)

const deleteSSORoleMapping = `-- name: DeleteSSORoleMapping :exec
DELETE FROM sso_role_mapping WHERE id = $1
`

func (q *Queries) DeleteSSORoleMapping(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteSSORoleMapping, id)
	return err
}

const listSSORoleMappings = `-- name: ListSSORoleMappings :many
SELECT id, entra_role, role, created_on FROM sso_role_mapping
ORDER BY entra_role
`

func (q *Queries) ListSSORoleMappings(ctx context.Context) ([]*SsoRoleMapping, error) {
	rows, err := q.db.Query(ctx, listSSORoleMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SsoRoleMapping
	for rows.Next() {
		var i SsoRoleMapping
		if err := rows.Scan(
			&i.ID,
			&i.EntraRole,
			&i.Role,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSSORoleMapping = `-- name: UpsertSSORoleMapping :one
INSERT INTO sso_role_mapping (entra_role, role)
VALUES ($1, $2)
ON CONFLICT (entra_role) DO UPDATE SET role = EXCLUDED.role
RETURNING id, entra_role, role, created_on
`

type UpsertSSORoleMappingParams struct {
	EntraRole string `json:"entra_role"`
	Role      string `json:"role"`
}

func (q *Queries) UpsertSSORoleMapping(ctx context.Context, arg UpsertSSORoleMappingParams) (*SsoRoleMapping, error) {
	row := q.db.QueryRow(ctx, upsertSSORoleMapping, arg.EntraRole, arg.Role)
	var i SsoRoleMapping
	err := row.Scan(
		&i.ID,
		&i.EntraRole,
		&i.Role,
		&i.CreatedOn,
	)
	return &i, err
}
