// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_session.sql

package db

import (
	"context"
	"time"
)

const deleteExpiredSSOSessions = `-- name: DeleteExpiredSSOSessions :exec
DELETE FROM sso_session WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSSOSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSSOSessions)
	return err
}

const deleteSSOSession = `-- name: DeleteSSOSession :exec
DELETE FROM sso_session WHERE key = $1
`

func (q *Queries) DeleteSSOSession(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSSOSession, key)
	return err
}

const deleteSSOSessionsByUser = `-- name: DeleteSSOSessionsByUser :exec
DELETE FROM sso_session WHERE user_id = $1
`

func (q *Queries) DeleteSSOSessionsByUser(ctx context.Context, userID int) error {
	_, err := q.db.Exec(ctx, deleteSSOSessionsByUser, userID)
	return err
}

const getSSOSession = `-- name: GetSSOSession :one
SELECT key, user_id, created_on, last_seen_at, expires_at FROM sso_session
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSSOSession(ctx context.Context, key string) (*SsoSession, error) {
	row := q.db.QueryRow(ctx, getSSOSession, key)
	var i SsoSession
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.CreatedOn,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const putSSOSession = `-- name: PutSSOSession :exec
INSERT INTO sso_session (key, user_id, created_on, last_seen_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    created_on = EXCLUDED.created_on,
    last_seen_at = EXCLUDED.last_seen_at,
    expires_at = EXCLUDED.expires_at
`

type PutSSOSessionParams struct {
	Key        string    `json:"key"`
	UserID     int       `json:"user_id"`
	CreatedOn  time.Time `json:"created_on"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) PutSSOSession(ctx context.Context, arg PutSSOSessionParams) error {
	_, err := q.db.Exec(ctx, putSSOSession,
		arg.Key,
		arg.UserID,
		arg.CreatedOn,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const touchSSOSession = `-- name: TouchSSOSession :exec
UPDATE sso_session
SET last_seen_at = $2, expires_at = $3
WHERE key = $1
`

type TouchSSOSessionParams struct {
	Key        string    `json:"key"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) TouchSSOSession(ctx context.Context, arg TouchSSOSessionParams) error {
	_, err := q.db.Exec(ctx, touchSSOSession, arg.Key, arg.LastSeenAt, arg.ExpiresAt)
	return err
}
