// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_journal.sql

package db

import (
	"context"
	"time"
)

const deleteTicketJournalsOlderThan = `-- name: DeleteTicketJournalsOlderThan :execrows
DELETE FROM ticket_journal
WHERE last_run < $1
`

func (q *Queries) DeleteTicketJournalsOlderThan(ctx context.Context, lastRun time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTicketJournalsOlderThan, lastRun)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTicketJournal = `-- name: GetTicketJournal :one
SELECT ticket_id, summary, board_name, company_name, contact_name, status_name, owner_name, last_trigger, last_outcome, had_error, first_seen, last_run, runs FROM ticket_journal
WHERE ticket_id = $1 LIMIT 1
`

func (q *Queries) GetTicketJournal(ctx context.Context, ticketID int) (*TicketJournal, error) {
	row := q.db.QueryRow(ctx, getTicketJournal, ticketID)
	var i TicketJournal
	err := row.Scan(
		&i.TicketID,
		&i.Summary,
		&i.BoardName,
		&i.CompanyName,
		&i.ContactName,
		&i.StatusName,
		&i.OwnerName,
		&i.LastTrigger,
		&i.LastOutcome,
		&i.HadError,
		&i.FirstSeen,
		&i.LastRun,
		&i.Runs,
	)
	return &i, err
}

const listTicketJournalSummaries = `-- name: ListTicketJournalSummaries :many
SELECT ticket_id, summary, board_name, company_name, contact_name, status_name,
       owner_name, last_trigger, last_outcome, had_error, first_seen, last_run
FROM ticket_journal
ORDER BY last_run DESC
LIMIT $1
`

type ListTicketJournalSummariesRow struct {
	TicketID    int       `json:"ticket_id"`
	Summary     string    `json:"summary"`
	BoardName   string    `json:"board_name"`
	CompanyName string    `json:"company_name"`
	ContactName string    `json:"contact_name"`
	StatusName  string    `json:"status_name"`
	OwnerName   string    `json:"owner_name"`
	LastTrigger string    `json:"last_trigger"`
	LastOutcome string    `json:"last_outcome"`
	HadError    bool      `json:"had_error"`
	FirstSeen   time.Time `json:"first_seen"`
	LastRun     time.Time `json:"last_run"`
}

func (q *Queries) ListTicketJournalSummaries(ctx context.Context, limit int32) ([]*ListTicketJournalSummariesRow, error) {
	rows, err := q.db.Query(ctx, listTicketJournalSummaries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTicketJournalSummariesRow
	for rows.Next() {
		var i ListTicketJournalSummariesRow
		if err := rows.Scan(
			&i.TicketID,
			&i.Summary,
			&i.BoardName,
			&i.CompanyName,
			&i.ContactName,
			&i.StatusName,
			&i.OwnerName,
			&i.LastTrigger,
			&i.LastOutcome,
			&i.HadError,
			&i.FirstSeen,
			&i.LastRun,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTicketJournal = `-- name: UpsertTicketJournal :one
INSERT INTO ticket_journal(
    ticket_id, summary, board_name, company_name, contact_name, status_name,
    owner_name, last_trigger, last_outcome, had_error, first_seen, last_run, runs
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (ticket_id) DO UPDATE SET
    summary      = EXCLUDED.summary,
    board_name   = EXCLUDED.board_name,
    company_name = EXCLUDED.company_name,
    contact_name = EXCLUDED.contact_name,
    status_name  = EXCLUDED.status_name,
    owner_name   = EXCLUDED.owner_name,
    last_trigger = EXCLUDED.last_trigger,
    last_outcome = EXCLUDED.last_outcome,
    had_error    = EXCLUDED.had_error,
    last_run     = EXCLUDED.last_run,
    runs         = EXCLUDED.runs
RETURNING ticket_id, summary, board_name, company_name, contact_name, status_name, owner_name, last_trigger, last_outcome, had_error, first_seen, last_run, runs
`

type UpsertTicketJournalParams struct {
	TicketID    int       `json:"ticket_id"`
	Summary     string    `json:"summary"`
	BoardName   string    `json:"board_name"`
	CompanyName string    `json:"company_name"`
	ContactName string    `json:"contact_name"`
	StatusName  string    `json:"status_name"`
	OwnerName   string    `json:"owner_name"`
	LastTrigger string    `json:"last_trigger"`
	LastOutcome string    `json:"last_outcome"`
	HadError    bool      `json:"had_error"`
	FirstSeen   time.Time `json:"first_seen"`
	LastRun     time.Time `json:"last_run"`
	Runs        []byte    `json:"runs"`
}

func (q *Queries) UpsertTicketJournal(ctx context.Context, arg UpsertTicketJournalParams) (*TicketJournal, error) {
	row := q.db.QueryRow(ctx, upsertTicketJournal,
		arg.TicketID,
		arg.Summary,
		arg.BoardName,
		arg.CompanyName,
		arg.ContactName,
		arg.StatusName,
		arg.OwnerName,
		arg.LastTrigger,
		arg.LastOutcome,
		arg.HadError,
		arg.FirstSeen,
		arg.LastRun,
		arg.Runs,
	)
	var i TicketJournal
	err := row.Scan(
		&i.TicketID,
		&i.Summary,
		&i.BoardName,
		&i.CompanyName,
		&i.ContactName,
		&i.StatusName,
		&i.OwnerName,
		&i.LastTrigger,
		&i.LastOutcome,
		&i.HadError,
		&i.FirstSeen,
		&i.LastRun,
		&i.Runs,
	)
	return &i, err
}
