// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_event.sql

package db

import (
	"context"
	"time"
)

const deleteTicketEventsBefore = `-- name: DeleteTicketEventsBefore :execrows
DELETE FROM ticket_event WHERE occurred_at < $1
`

func (q *Queries) DeleteTicketEventsBefore(ctx context.Context, occurredAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTicketEventsBefore, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTicketEvent = `-- name: InsertTicketEvent :one
INSERT INTO ticket_event (ticket_id, run_id, kind, source, dry_run, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ticket_id, run_id, kind, source, dry_run, payload, occurred_at
`

type InsertTicketEventParams struct {
	TicketID   int       `json:"ticket_id"`
	RunID      string    `json:"run_id"`
	Kind       string    `json:"kind"`
	Source     string    `json:"source"`
	DryRun     bool      `json:"dry_run"`
	Payload    []byte    `json:"payload"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) InsertTicketEvent(ctx context.Context, arg InsertTicketEventParams) (*TicketEvent, error) {
	row := q.db.QueryRow(ctx, insertTicketEvent,
		arg.TicketID,
		arg.RunID,
		arg.Kind,
		arg.Source,
		arg.DryRun,
		arg.Payload,
		arg.OccurredAt,
	)
	var i TicketEvent
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.RunID,
		&i.Kind,
		&i.Source,
		&i.DryRun,
		&i.Payload,
		&i.OccurredAt,
	)
	return &i, err
}

const listRecentTicketEvents = `-- name: ListRecentTicketEvents :many
SELECT id, ticket_id, run_id, kind, source, dry_run, payload, occurred_at FROM ticket_event
WHERE ($1::text IS NULL OR kind = $1::text)
ORDER BY id DESC
LIMIT $2
`

type ListRecentTicketEventsParams struct {
	Kind *string `json:"kind"`
	Lim  int32   `json:"lim"`
}

func (q *Queries) ListRecentTicketEvents(ctx context.Context, arg ListRecentTicketEventsParams) ([]*TicketEvent, error) {
	rows, err := q.db.Query(ctx, listRecentTicketEvents, arg.Kind, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TicketEvent
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.RunID,
			&i.Kind,
			&i.Source,
			&i.DryRun,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketEventsByRun = `-- name: ListTicketEventsByRun :many
SELECT id, ticket_id, run_id, kind, source, dry_run, payload, occurred_at FROM ticket_event
WHERE run_id = $1
ORDER BY id
`

func (q *Queries) ListTicketEventsByRun(ctx context.Context, runID string) ([]*TicketEvent, error) {
	rows, err := q.db.Query(ctx, listTicketEventsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TicketEvent
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.RunID,
			&i.Kind,
			&i.Source,
			&i.DryRun,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketEventsByTicket = `-- name: ListTicketEventsByTicket :many
SELECT id, ticket_id, run_id, kind, source, dry_run, payload, occurred_at FROM ticket_event
WHERE ticket_id = $1
  AND ($2::bigint IS NULL OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListTicketEventsByTicketParams struct {
	TicketID int    `json:"ticket_id"`
	BeforeID *int64 `json:"before_id"`
	Lim      int32  `json:"lim"`
}

func (q *Queries) ListTicketEventsByTicket(ctx context.Context, arg ListTicketEventsByTicketParams) ([]*TicketEvent, error) {
	rows, err := q.db.Query(ctx, listTicketEventsByTicket, arg.TicketID, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TicketEvent
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.RunID,
			&i.Kind,
			&i.Source,
			&i.DryRun,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
