// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: totp_recovery.sql

package db

import (
	"context"
)

const deleteTOTPRecoveryCodes = `-- name: DeleteTOTPRecoveryCodes :exec
DELETE FROM totp_recovery_code WHERE user_id = $1
`

func (q *Queries) DeleteTOTPRecoveryCodes(ctx context.Context, userID int) error {
	_, err := q.db.Exec(ctx, deleteTOTPRecoveryCodes, userID)
	return err
}

const getUnusedTOTPRecoveryCodeByHash = `-- name: GetUnusedTOTPRecoveryCodeByHash :one
SELECT id, user_id, code_hash, used, created_on FROM totp_recovery_code
WHERE user_id = $1 AND code_hash = $2 AND used = FALSE
LIMIT 1
`

type GetUnusedTOTPRecoveryCodeByHashParams struct {
	UserID   int    `json:"user_id"`
	CodeHash []byte `json:"code_hash"`
}

func (q *Queries) GetUnusedTOTPRecoveryCodeByHash(ctx context.Context, arg GetUnusedTOTPRecoveryCodeByHashParams) (*TotpRecoveryCode, error) {
	row := q.db.QueryRow(ctx, getUnusedTOTPRecoveryCodeByHash, arg.UserID, arg.CodeHash)
	var i TotpRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Used,
		&i.CreatedOn,
	)
	return &i, err
}

const insertTOTPRecoveryCode = `-- name: InsertTOTPRecoveryCode :exec
INSERT INTO totp_recovery_code (user_id, code_hash)
VALUES ($1, $2)
`

type InsertTOTPRecoveryCodeParams struct {
	UserID   int    `json:"user_id"`
	CodeHash []byte `json:"code_hash"`
}

func (q *Queries) InsertTOTPRecoveryCode(ctx context.Context, arg InsertTOTPRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertTOTPRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const markTOTPRecoveryCodeUsed = `-- name: MarkTOTPRecoveryCodeUsed :exec
UPDATE totp_recovery_code SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkTOTPRecoveryCodeUsed(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, markTOTPRecoveryCodeUsed, id)
	return err
}
