// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transformer_rule.sql

package db

import (
	"context"
)

const checkTransformerRuleExists = `-- name: CheckTransformerRuleExists :one
SELECT EXISTS (
    SELECT 1
    FROM transformer_rule
    WHERE id = $1
) AS exists
`

func (q *Queries) CheckTransformerRuleExists(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRow(ctx, checkTransformerRuleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteTransformerRule = `-- name: DeleteTransformerRule :exec
DELETE FROM transformer_rule
WHERE id = $1
`

func (q *Queries) DeleteTransformerRule(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTransformerRule, id)
	return err
}

const getTransformerRule = `-- name: GetTransformerRule :one
SELECT id, name, action, cw_board_id, config, apply_on, priority, enabled, created_on, updated_on, conditions FROM transformer_rule
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransformerRule(ctx context.Context, id int) (*TransformerRule, error) {
	row := q.db.QueryRow(ctx, getTransformerRule, id)
	var i TransformerRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Action,
		&i.CwBoardID,
		&i.Config,
		&i.ApplyOn,
		&i.Priority,
		&i.Enabled,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Conditions,
	)
	return &i, err
}

const insertTransformerRule = `-- name: InsertTransformerRule :one
INSERT INTO transformer_rule(name, action, cw_board_id, config, conditions, apply_on, priority, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, action, cw_board_id, config, apply_on, priority, enabled, created_on, updated_on, conditions
`

type InsertTransformerRuleParams struct {
	Name       string `json:"name"`
	Action     string `json:"action"`
	CwBoardID  *int   `json:"cw_board_id"`
	Config     []byte `json:"config"`
	Conditions []byte `json:"conditions"`
	ApplyOn    string `json:"apply_on"`
	Priority   int    `json:"priority"`
	Enabled    bool   `json:"enabled"`
}

func (q *Queries) InsertTransformerRule(ctx context.Context, arg InsertTransformerRuleParams) (*TransformerRule, error) {
	row := q.db.QueryRow(ctx, insertTransformerRule,
		arg.Name,
		arg.Action,
		arg.CwBoardID,
		arg.Config,
		arg.Conditions,
		arg.ApplyOn,
		arg.Priority,
		arg.Enabled,
	)
	var i TransformerRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Action,
		&i.CwBoardID,
		&i.Config,
		&i.ApplyOn,
		&i.Priority,
		&i.Enabled,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Conditions,
	)
	return &i, err
}

const listEnabledTransformerRules = `-- name: ListEnabledTransformerRules :many
SELECT id, name, action, cw_board_id, config, apply_on, priority, enabled, created_on, updated_on, conditions FROM transformer_rule
WHERE enabled = true
ORDER BY priority, id
`

func (q *Queries) ListEnabledTransformerRules(ctx context.Context) ([]*TransformerRule, error) {
	rows, err := q.db.Query(ctx, listEnabledTransformerRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TransformerRule
	for rows.Next() {
		var i TransformerRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Action,
			&i.CwBoardID,
			&i.Config,
			&i.ApplyOn,
			&i.Priority,
			&i.Enabled,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransformerRules = `-- name: ListTransformerRules :many
SELECT id, name, action, cw_board_id, config, apply_on, priority, enabled, created_on, updated_on, conditions FROM transformer_rule
ORDER BY priority, id
`

func (q *Queries) ListTransformerRules(ctx context.Context) ([]*TransformerRule, error) {
	rows, err := q.db.Query(ctx, listTransformerRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TransformerRule
	for rows.Next() {
		var i TransformerRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Action,
			&i.CwBoardID,
			&i.Config,
			&i.ApplyOn,
			&i.Priority,
			&i.Enabled,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransformerRule = `-- name: UpdateTransformerRule :one
UPDATE transformer_rule
SET
    name        = $2,
    action      = $3,
    cw_board_id = $4,
    config      = $5,
    conditions  = $6,
    apply_on    = $7,
    priority    = $8,
    enabled     = $9,
    updated_on  = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, action, cw_board_id, config, apply_on, priority, enabled, created_on, updated_on, conditions
`

type UpdateTransformerRuleParams struct {
	ID         int    `json:"id"`
	Name       string `json:"name"`
	Action     string `json:"action"`
	CwBoardID  *int   `json:"cw_board_id"`
	Config     []byte `json:"config"`
	Conditions []byte `json:"conditions"`
	ApplyOn    string `json:"apply_on"`
	Priority   int    `json:"priority"`
	Enabled    bool   `json:"enabled"`
}

func (q *Queries) UpdateTransformerRule(ctx context.Context, arg UpdateTransformerRuleParams) (*TransformerRule, error) {
	row := q.db.QueryRow(ctx, updateTransformerRule,
		arg.ID,
		arg.Name,
		arg.Action,
		arg.CwBoardID,
		arg.Config,
		arg.Conditions,
		arg.ApplyOn,
		arg.Priority,
		arg.Enabled,
	)
	var i TransformerRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Action,
		&i.CwBoardID,
		&i.Config,
		&i.ApplyOn,
		&i.Priority,
		&i.Enabled,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Conditions,
	)
	return &i, err
}
