// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transformer_run.sql

package db

import (
	"context"
)

const checkTransformerRunExists = `-- name: CheckTransformerRunExists :one
SELECT EXISTS (
    SELECT 1
    FROM transformer_run
    WHERE ticket_id = $1 AND rule_id = $2
) AS exists
`

type CheckTransformerRunExistsParams struct {
	TicketID int `json:"ticket_id"`
	RuleID   int `json:"rule_id"`
}

func (q *Queries) CheckTransformerRunExists(ctx context.Context, arg CheckTransformerRunExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTransformerRunExists, arg.TicketID, arg.RuleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertTransformerRun = `-- name: InsertTransformerRun :exec
INSERT INTO transformer_run(ticket_id, rule_id)
VALUES ($1, $2)
ON CONFLICT (ticket_id, rule_id) DO NOTHING
`

type InsertTransformerRunParams struct {
	TicketID int `json:"ticket_id"`
	RuleID   int `json:"rule_id"`
}

func (q *Queries) InsertTransformerRun(ctx context.Context, arg InsertTransformerRunParams) error {
	_, err := q.db.Exec(ctx, insertTransformerRun, arg.TicketID, arg.RuleID)
	return err
}
