// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webex_recipient.sql

package db

import (
	"context"
	"time"
)

const deleteWebexRecipient = `-- name: DeleteWebexRecipient :exec
DELETE FROM webex_recipient
WHERE id = $1
`

func (q *Queries) DeleteWebexRecipient(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteWebexRecipient, id)
	return err
}

const getWebexRecipient = `-- name: GetWebexRecipient :one
SELECT id, webex_id, name, email, type, last_activity, created_on, updated_on FROM webex_recipient
WHERE id = $1
`

func (q *Queries) GetWebexRecipient(ctx context.Context, id int) (*WebexRecipient, error) {
	row := q.db.QueryRow(ctx, getWebexRecipient, id)
	var i WebexRecipient
	err := row.Scan(
		&i.ID,
		&i.WebexID,
		&i.Name,
		&i.Email,
		&i.Type,
		&i.LastActivity,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const getWebexRecipientByWebexID = `-- name: GetWebexRecipientByWebexID :one
SELECT id, webex_id, name, email, type, last_activity, created_on, updated_on FROM webex_recipient
WHERE webex_id = $1
`

func (q *Queries) GetWebexRecipientByWebexID(ctx context.Context, webexID string) (*WebexRecipient, error) {
	row := q.db.QueryRow(ctx, getWebexRecipientByWebexID, webexID)
	var i WebexRecipient
	err := row.Scan(
		&i.ID,
		&i.WebexID,
		&i.Name,
		&i.Email,
		&i.Type,
		&i.LastActivity,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const listByEmail = `-- name: ListByEmail :many
SELECT id, webex_id, name, email, type, last_activity, created_on, updated_on FROM webex_recipient
WHERE email = $1
`

func (q *Queries) ListByEmail(ctx context.Context, email *string) ([]*WebexRecipient, error) {
	rows, err := q.db.Query(ctx, listByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebexRecipient
	for rows.Next() {
		var i WebexRecipient
		if err := rows.Scan(
			&i.ID,
			&i.WebexID,
			&i.Name,
			&i.Email,
			&i.Type,
			&i.LastActivity,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebexPeople = `-- name: ListWebexPeople :many
SELECT id, webex_id, name, email, type, last_activity, created_on, updated_on FROM webex_recipient
WHERE type = 'person'
`

func (q *Queries) ListWebexPeople(ctx context.Context) ([]*WebexRecipient, error) {
	rows, err := q.db.Query(ctx, listWebexPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebexRecipient
	for rows.Next() {
		var i WebexRecipient
		if err := rows.Scan(
			&i.ID,
			&i.WebexID,
			&i.Name,
			&i.Email,
			&i.Type,
			&i.LastActivity,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebexRecipients = `-- name: ListWebexRecipients :many
SELECT id, webex_id, name, email, type, last_activity, created_on, updated_on FROM webex_recipient
ORDER BY id
`

func (q *Queries) ListWebexRecipients(ctx context.Context) ([]*WebexRecipient, error) {
	rows, err := q.db.Query(ctx, listWebexRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebexRecipient
	for rows.Next() {
		var i WebexRecipient
		if err := rows.Scan(
			&i.ID,
			&i.WebexID,
			&i.Name,
			&i.Email,
			&i.Type,
			&i.LastActivity,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebexRooms = `-- name: ListWebexRooms :many
SELECT id, webex_id, name, email, type, last_activity, created_on, updated_on FROM webex_recipient
WHERE type = 'room'
`

func (q *Queries) ListWebexRooms(ctx context.Context) ([]*WebexRecipient, error) {
	rows, err := q.db.Query(ctx, listWebexRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebexRecipient
	for rows.Next() {
		var i WebexRecipient
		if err := rows.Scan(
			&i.ID,
			&i.WebexID,
			&i.Name,
			&i.Email,
			&i.Type,
			&i.LastActivity,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWebexRecipient = `-- name: SoftDeleteWebexRecipient :exec
UPDATE cw_board
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteWebexRecipient(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteWebexRecipient, id)
	return err
}

const upsertWebexRecipient = `-- name: UpsertWebexRecipient :one
INSERT INTO webex_recipient
(webex_id, name, type, email, last_activity)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (webex_id) DO UPDATE SET
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    email = EXCLUDED.email,
    last_activity = EXCLUDED.last_activity,
    updated_on = NOW()
RETURNING id, webex_id, name, email, type, last_activity, created_on, updated_on
`

type UpsertWebexRecipientParams struct {
	WebexID      string    `json:"webex_id"`
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	Email        *string   `json:"email"`
	LastActivity time.Time `json:"last_activity"`
}

func (q *Queries) UpsertWebexRecipient(ctx context.Context, arg UpsertWebexRecipientParams) (*WebexRecipient, error) {
	row := q.db.QueryRow(ctx, upsertWebexRecipient,
		arg.WebexID,
		arg.Name,
		arg.Type,
		arg.Email,
		arg.LastActivity,
	)
	var i WebexRecipient
	err := row.Scan(
		&i.ID,
		&i.WebexID,
		&i.Name,
		&i.Email,
		&i.Type,
		&i.LastActivity,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}
