// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_catchup.sql

package db

import (
	"context"
	"time"
)

const getWebhookCatchup = `-- name: GetWebhookCatchup :one
SELECT id, checked_through, last_run_at, last_queued, last_error FROM webhook_catchup WHERE id = 1
`

func (q *Queries) GetWebhookCatchup(ctx context.Context) (*WebhookCatchup, error) {
	row := q.db.QueryRow(ctx, getWebhookCatchup)
	var i WebhookCatchup
	err := row.Scan(
		&i.ID,
		&i.CheckedThrough,
		&i.LastRunAt,
		&i.LastQueued,
		&i.LastError,
	)
	return &i, err
}

const saveWebhookCatchup = `-- name: SaveWebhookCatchup :one
INSERT INTO webhook_catchup (id, checked_through, last_run_at, last_queued, last_error)
VALUES (1, $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    checked_through = EXCLUDED.checked_through,
    last_run_at = EXCLUDED.last_run_at,
    last_queued = EXCLUDED.last_queued,
    last_error = EXCLUDED.last_error
RETURNING id, checked_through, last_run_at, last_queued, last_error
`

type SaveWebhookCatchupParams struct {
	CheckedThrough *time.Time `json:"checked_through"`
	LastRunAt      *time.Time `json:"last_run_at"`
	LastQueued     int        `json:"last_queued"`
	LastError      *string    `json:"last_error"`
}

func (q *Queries) SaveWebhookCatchup(ctx context.Context, arg SaveWebhookCatchupParams) (*WebhookCatchup, error) {
	row := q.db.QueryRow(ctx, saveWebhookCatchup,
		arg.CheckedThrough,
		arg.LastRunAt,
		arg.LastQueued,
		arg.LastError,
	)
	var i WebhookCatchup
	err := row.Scan(
		&i.ID,
		&i.CheckedThrough,
		&i.LastRunAt,
		&i.LastQueued,
		&i.LastError,
	)
	return &i, err
}
