// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_intake.sql

package db

import (
	"context"
	"time"
)

const claimWebhookIntake = `-- name: ClaimWebhookIntake :one
UPDATE webhook_intake SET status = 'processing', attempts = attempts + 1
WHERE id = (
    SELECT w.id FROM webhook_intake w
    WHERE w.status = 'pending'
      AND w.next_attempt_at <= NOW()
      AND NOT EXISTS (
          SELECT 1 FROM webhook_intake o
          WHERE o.ticket_id = w.ticket_id
            AND o.status IN ('pending', 'processing')
            AND o.id < w.id
      )
    ORDER BY w.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, ticket_id, action, payload, status, attempts, next_attempt_at, last_error, received_at, finished_at
`

// Claims the oldest ready row whose ticket has no older open row, so one ticket's webhooks are
// processed strictly in arrival order and never two at once.
func (q *Queries) ClaimWebhookIntake(ctx context.Context) (*WebhookIntake, error) {
	row := q.db.QueryRow(ctx, claimWebhookIntake)
	var i WebhookIntake
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ReceivedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const countWebhookIntakeByHour = `-- name: CountWebhookIntakeByHour :many
SELECT date_trunc('hour', received_at)::timestamptz AS hour, COUNT(*)::bigint AS n
FROM webhook_intake
WHERE received_at >= $1
GROUP BY 1
ORDER BY 1
`

type CountWebhookIntakeByHourRow struct {
	Hour time.Time `json:"hour"`
	N    int64     `json:"n"`
}

func (q *Queries) CountWebhookIntakeByHour(ctx context.Context, receivedAt time.Time) ([]*CountWebhookIntakeByHourRow, error) {
	rows, err := q.db.Query(ctx, countWebhookIntakeByHour, receivedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CountWebhookIntakeByHourRow
	for rows.Next() {
		var i CountWebhookIntakeByHourRow
		if err := rows.Scan(&i.Hour, &i.N); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhookIntakeByStatus = `-- name: CountWebhookIntakeByStatus :many
SELECT status, COUNT(*)::bigint AS n FROM webhook_intake GROUP BY status
`

type CountWebhookIntakeByStatusRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

func (q *Queries) CountWebhookIntakeByStatus(ctx context.Context) ([]*CountWebhookIntakeByStatusRow, error) {
	rows, err := q.db.Query(ctx, countWebhookIntakeByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CountWebhookIntakeByStatusRow
	for rows.Next() {
		var i CountWebhookIntakeByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhookIntakeReceivedSince = `-- name: CountWebhookIntakeReceivedSince :one
SELECT COUNT(*)::bigint FROM webhook_intake WHERE received_at >= $1
`

func (q *Queries) CountWebhookIntakeReceivedSince(ctx context.Context, receivedAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookIntakeReceivedSince, receivedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFinishedWebhookIntakeBefore = `-- name: DeleteFinishedWebhookIntakeBefore :execrows
DELETE FROM webhook_intake
WHERE status IN ('done', 'discarded') AND finished_at < $1
`

func (q *Queries) DeleteFinishedWebhookIntakeBefore(ctx context.Context, finishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedWebhookIntakeBefore, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const discardWebhookIntake = `-- name: DiscardWebhookIntake :one
UPDATE webhook_intake SET status = 'discarded', finished_at = NOW()
WHERE id = $1 AND status = 'failed'
RETURNING id, ticket_id, action, payload, status, attempts, next_attempt_at, last_error, received_at, finished_at
`

func (q *Queries) DiscardWebhookIntake(ctx context.Context, id int64) (*WebhookIntake, error) {
	row := q.db.QueryRow(ctx, discardWebhookIntake, id)
	var i WebhookIntake
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ReceivedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const failWebhookIntake = `-- name: FailWebhookIntake :exec
UPDATE webhook_intake SET status = 'failed', last_error = $2, finished_at = NOW()
WHERE id = $1
`

type FailWebhookIntakeParams struct {
	ID        int64   `json:"id"`
	LastError *string `json:"last_error"`
}

func (q *Queries) FailWebhookIntake(ctx context.Context, arg FailWebhookIntakeParams) error {
	_, err := q.db.Exec(ctx, failWebhookIntake, arg.ID, arg.LastError)
	return err
}

const finishWebhookIntake = `-- name: FinishWebhookIntake :exec
UPDATE webhook_intake SET status = 'done', last_error = NULL, finished_at = NOW()
WHERE id = $1
`

func (q *Queries) FinishWebhookIntake(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, finishWebhookIntake, id)
	return err
}

const insertWebhookIntake = `-- name: InsertWebhookIntake :one
INSERT INTO webhook_intake (ticket_id, action, payload)
VALUES ($1, $2, $3)
RETURNING id, ticket_id, action, payload, status, attempts, next_attempt_at, last_error, received_at, finished_at
`

type InsertWebhookIntakeParams struct {
	TicketID int    `json:"ticket_id"`
	Action   string `json:"action"`
	Payload  []byte `json:"payload"`
}

func (q *Queries) InsertWebhookIntake(ctx context.Context, arg InsertWebhookIntakeParams) (*WebhookIntake, error) {
	row := q.db.QueryRow(ctx, insertWebhookIntake, arg.TicketID, arg.Action, arg.Payload)
	var i WebhookIntake
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ReceivedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const lastWebhookIntakeReceivedAt = `-- name: LastWebhookIntakeReceivedAt :one
SELECT received_at FROM webhook_intake ORDER BY received_at DESC LIMIT 1
`

func (q *Queries) LastWebhookIntakeReceivedAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastWebhookIntakeReceivedAt)
	var received_at time.Time
	err := row.Scan(&received_at)
	return received_at, err
}

const listWebhookIntake = `-- name: ListWebhookIntake :many
SELECT id, ticket_id, action, payload, status, attempts, next_attempt_at, last_error, received_at, finished_at FROM webhook_intake
WHERE ($1::text IS NULL OR status = $1::text)
ORDER BY id DESC
LIMIT $2
`

type ListWebhookIntakeParams struct {
	Status *string `json:"status"`
	Lim    int32   `json:"lim"`
}

func (q *Queries) ListWebhookIntake(ctx context.Context, arg ListWebhookIntakeParams) ([]*WebhookIntake, error) {
	rows, err := q.db.Query(ctx, listWebhookIntake, arg.Status, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebhookIntake
	for rows.Next() {
		var i WebhookIntake
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.ReceivedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleWebhookIntake = `-- name: RescheduleWebhookIntake :exec
UPDATE webhook_intake SET status = 'pending', next_attempt_at = $2, last_error = $3
WHERE id = $1
`

type RescheduleWebhookIntakeParams struct {
	ID            int64     `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     *string   `json:"last_error"`
}

func (q *Queries) RescheduleWebhookIntake(ctx context.Context, arg RescheduleWebhookIntakeParams) error {
	_, err := q.db.Exec(ctx, rescheduleWebhookIntake, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const resetProcessingWebhookIntake = `-- name: ResetProcessingWebhookIntake :execrows
UPDATE webhook_intake SET status = 'pending', next_attempt_at = NOW()
WHERE status = 'processing'
`

// Rows left in processing by a crash or restart go back to pending.
func (q *Queries) ResetProcessingWebhookIntake(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetProcessingWebhookIntake)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryWebhookIntake = `-- name: RetryWebhookIntake :one
UPDATE webhook_intake
SET status = 'pending', attempts = 0, next_attempt_at = NOW(), last_error = NULL, finished_at = NULL
WHERE id = $1 AND status = 'failed'
RETURNING id, ticket_id, action, payload, status, attempts, next_attempt_at, last_error, received_at, finished_at
`

func (q *Queries) RetryWebhookIntake(ctx context.Context, id int64) (*WebhookIntake, error) {
	row := q.db.QueryRow(ctx, retryWebhookIntake, id)
	var i WebhookIntake
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ReceivedAt,
		&i.FinishedAt,
	)
	return &i, err
}
