// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package db

import (
	"context"
	"time"
)

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflow
WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT w.id, w.board_id, w.name, w.enabled, w.dry_run, w.rules, w.created_on, w.updated_on, b.name AS board_name
FROM workflow w
JOIN cw_board b ON b.id = w.board_id
WHERE w.id = $1 LIMIT 1
`

type GetWorkflowRow struct {
	ID        int       `json:"id"`
	BoardID   int       `json:"board_id"`
	Name      string    `json:"name"`
	Enabled   bool      `json:"enabled"`
	DryRun    bool      `json:"dry_run"`
	Rules     []byte    `json:"rules"`
	CreatedOn time.Time `json:"created_on"`
	UpdatedOn time.Time `json:"updated_on"`
	BoardName string    `json:"board_name"`
}

func (q *Queries) GetWorkflow(ctx context.Context, id int) (*GetWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i GetWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Enabled,
		&i.DryRun,
		&i.Rules,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.BoardName,
	)
	return &i, err
}

const getWorkflowByBoard = `-- name: GetWorkflowByBoard :one
SELECT w.id, w.board_id, w.name, w.enabled, w.dry_run, w.rules, w.created_on, w.updated_on, b.name AS board_name
FROM workflow w
JOIN cw_board b ON b.id = w.board_id
WHERE w.board_id = $1 LIMIT 1
`

type GetWorkflowByBoardRow struct {
	ID        int       `json:"id"`
	BoardID   int       `json:"board_id"`
	Name      string    `json:"name"`
	Enabled   bool      `json:"enabled"`
	DryRun    bool      `json:"dry_run"`
	Rules     []byte    `json:"rules"`
	CreatedOn time.Time `json:"created_on"`
	UpdatedOn time.Time `json:"updated_on"`
	BoardName string    `json:"board_name"`
}

func (q *Queries) GetWorkflowByBoard(ctx context.Context, boardID int) (*GetWorkflowByBoardRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByBoard, boardID)
	var i GetWorkflowByBoardRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Enabled,
		&i.DryRun,
		&i.Rules,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.BoardName,
	)
	return &i, err
}

const insertWorkflow = `-- name: InsertWorkflow :one
INSERT INTO workflow (board_id, name, enabled, dry_run, rules)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_id, name, enabled, dry_run, rules, created_on, updated_on
`

type InsertWorkflowParams struct {
	BoardID int    `json:"board_id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
	DryRun  bool   `json:"dry_run"`
	Rules   []byte `json:"rules"`
}

func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) (*Workflow, error) {
	row := q.db.QueryRow(ctx, insertWorkflow,
		arg.BoardID,
		arg.Name,
		arg.Enabled,
		arg.DryRun,
		arg.Rules,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Enabled,
		&i.DryRun,
		&i.Rules,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT w.id, w.board_id, w.name, w.enabled, w.dry_run, w.rules, w.created_on, w.updated_on, b.name AS board_name
FROM workflow w
JOIN cw_board b ON b.id = w.board_id
ORDER BY b.name, w.id
`

type ListWorkflowsRow struct {
	ID        int       `json:"id"`
	BoardID   int       `json:"board_id"`
	Name      string    `json:"name"`
	Enabled   bool      `json:"enabled"`
	DryRun    bool      `json:"dry_run"`
	Rules     []byte    `json:"rules"`
	CreatedOn time.Time `json:"created_on"`
	UpdatedOn time.Time `json:"updated_on"`
	BoardName string    `json:"board_name"`
}

func (q *Queries) ListWorkflows(ctx context.Context) ([]*ListWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListWorkflowsRow
	for rows.Next() {
		var i ListWorkflowsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Enabled,
			&i.DryRun,
			&i.Rules,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.BoardName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflow
SET
    name = $2,
    enabled = $3,
    dry_run = $4,
    rules = $5,
    updated_on = NOW()
WHERE id = $1
RETURNING id, board_id, name, enabled, dry_run, rules, created_on, updated_on
`

type UpdateWorkflowParams struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
	DryRun  bool   `json:"dry_run"`
	Rules   []byte `json:"rules"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (*Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.DryRun,
		arg.Rules,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Enabled,
		&i.DryRun,
		&i.Rules,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const workflowExistsForBoard = `-- name: WorkflowExistsForBoard :one
SELECT EXISTS (
    SELECT 1 FROM workflow WHERE board_id = $1
) AS exists
`

func (q *Queries) WorkflowExistsForBoard(ctx context.Context, boardID int) (bool, error) {
	row := q.db.QueryRow(ctx, workflowExistsForBoard, boardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
