// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package db

import (
	"context"
)

const checkWorkflowExists = `-- name: CheckWorkflowExists :one
SELECT EXISTS (
    SELECT 1
    FROM workflow
    WHERE id = $1
) AS exists
`

func (q *Queries) CheckWorkflowExists(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkflowExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflow
WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, name, cw_board_id, on_ticket_action, conditions, actions, priority, enabled, created_on, updated_on, simulation_mode FROM workflow
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkflow(ctx context.Context, id int) (*Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CwBoardID,
		&i.OnTicketAction,
		&i.Conditions,
		&i.Actions,
		&i.Priority,
		&i.Enabled,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.SimulationMode,
	)
	return &i, err
}

const insertWorkflow = `-- name: InsertWorkflow :one
INSERT INTO workflow(name, cw_board_id, on_ticket_action, conditions, actions, priority, enabled, simulation_mode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, cw_board_id, on_ticket_action, conditions, actions, priority, enabled, created_on, updated_on, simulation_mode
`

type InsertWorkflowParams struct {
	Name           string `json:"name"`
	CwBoardID      int    `json:"cw_board_id"`
	OnTicketAction string `json:"on_ticket_action"`
	Conditions     []byte `json:"conditions"`
	Actions        []byte `json:"actions"`
	Priority       int    `json:"priority"`
	Enabled        bool   `json:"enabled"`
	SimulationMode bool   `json:"simulation_mode"`
}

func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) (*Workflow, error) {
	row := q.db.QueryRow(ctx, insertWorkflow,
		arg.Name,
		arg.CwBoardID,
		arg.OnTicketAction,
		arg.Conditions,
		arg.Actions,
		arg.Priority,
		arg.Enabled,
		arg.SimulationMode,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CwBoardID,
		&i.OnTicketAction,
		&i.Conditions,
		&i.Actions,
		&i.Priority,
		&i.Enabled,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.SimulationMode,
	)
	return &i, err
}

const listEnabledWorkflows = `-- name: ListEnabledWorkflows :many
SELECT id, name, cw_board_id, on_ticket_action, conditions, actions, priority, enabled, created_on, updated_on, simulation_mode FROM workflow
WHERE enabled = true
ORDER BY priority, id
`

func (q *Queries) ListEnabledWorkflows(ctx context.Context) ([]*Workflow, error) {
	rows, err := q.db.Query(ctx, listEnabledWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CwBoardID,
			&i.OnTicketAction,
			&i.Conditions,
			&i.Actions,
			&i.Priority,
			&i.Enabled,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.SimulationMode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, cw_board_id, on_ticket_action, conditions, actions, priority, enabled, created_on, updated_on, simulation_mode FROM workflow
ORDER BY priority, id
`

func (q *Queries) ListWorkflows(ctx context.Context) ([]*Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CwBoardID,
			&i.OnTicketAction,
			&i.Conditions,
			&i.Actions,
			&i.Priority,
			&i.Enabled,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.SimulationMode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflow
SET
    name             = $2,
    cw_board_id      = $3,
    on_ticket_action = $4,
    conditions       = $5,
    actions          = $6,
    priority         = $7,
    enabled          = $8,
    simulation_mode  = $9,
    updated_on       = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, cw_board_id, on_ticket_action, conditions, actions, priority, enabled, created_on, updated_on, simulation_mode
`

type UpdateWorkflowParams struct {
	ID             int    `json:"id"`
	Name           string `json:"name"`
	CwBoardID      int    `json:"cw_board_id"`
	OnTicketAction string `json:"on_ticket_action"`
	Conditions     []byte `json:"conditions"`
	Actions        []byte `json:"actions"`
	Priority       int    `json:"priority"`
	Enabled        bool   `json:"enabled"`
	SimulationMode bool   `json:"simulation_mode"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (*Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.CwBoardID,
		arg.OnTicketAction,
		arg.Conditions,
		arg.Actions,
		arg.Priority,
		arg.Enabled,
		arg.SimulationMode,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CwBoardID,
		&i.OnTicketAction,
		&i.Conditions,
		&i.Actions,
		&i.Priority,
		&i.Enabled,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.SimulationMode,
	)
	return &i, err
}
