// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_run.sql

package db

import (
	"context"
)

const checkWorkflowRunExists = `-- name: CheckWorkflowRunExists :one
SELECT EXISTS (
    SELECT 1
    FROM workflow_run
    WHERE ticket_id = $1 AND workflow_id = $2 AND action_index = $3
) AS exists
`

type CheckWorkflowRunExistsParams struct {
	TicketID    int `json:"ticket_id"`
	WorkflowID  int `json:"workflow_id"`
	ActionIndex int `json:"action_index"`
}

func (q *Queries) CheckWorkflowRunExists(ctx context.Context, arg CheckWorkflowRunExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkflowRunExists, arg.TicketID, arg.WorkflowID, arg.ActionIndex)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertWorkflowRun = `-- name: InsertWorkflowRun :exec
INSERT INTO workflow_run(ticket_id, workflow_id, action_index)
VALUES ($1, $2, $3)
ON CONFLICT (ticket_id, workflow_id, action_index) DO NOTHING
`

type InsertWorkflowRunParams struct {
	TicketID    int `json:"ticket_id"`
	WorkflowID  int `json:"workflow_id"`
	ActionIndex int `json:"action_index"`
}

func (q *Queries) InsertWorkflowRun(ctx context.Context, arg InsertWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowRun, arg.TicketID, arg.WorkflowID, arg.ActionIndex)
	return err
}
