// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_run.sql

package db

import (
	"context"
	"time"
)

const deleteWorkflowRunsBefore = `-- name: DeleteWorkflowRunsBefore :execrows
DELETE FROM workflow_run WHERE started_at < $1
`

func (q *Queries) DeleteWorkflowRunsBefore(ctx context.Context, startedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowRunsBefore, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT run_id, ticket_id, board_id, workflow_id, workflow_name, event, source, dry_run, started_at, duration_ms, steps, actions, writes, notif_sent, notif_would_send, notif_none, errors, outcome FROM workflow_run WHERE run_id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, runID string) (*WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, runID)
	var i WorkflowRun
	err := row.Scan(
		&i.RunID,
		&i.TicketID,
		&i.BoardID,
		&i.WorkflowID,
		&i.WorkflowName,
		&i.Event,
		&i.Source,
		&i.DryRun,
		&i.StartedAt,
		&i.DurationMs,
		&i.Steps,
		&i.Actions,
		&i.Writes,
		&i.NotifSent,
		&i.NotifWouldSend,
		&i.NotifNone,
		&i.Errors,
		&i.Outcome,
	)
	return &i, err
}

const insertWorkflowRun = `-- name: InsertWorkflowRun :exec
INSERT INTO workflow_run (run_id, ticket_id, board_id, workflow_id, workflow_name, event, source, dry_run,
    started_at, duration_ms, steps, actions, writes, notif_sent, notif_would_send, notif_none, errors, outcome)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (run_id) DO NOTHING
`

type InsertWorkflowRunParams struct {
	RunID          string    `json:"run_id"`
	TicketID       int       `json:"ticket_id"`
	BoardID        int       `json:"board_id"`
	WorkflowID     *int      `json:"workflow_id"`
	WorkflowName   string    `json:"workflow_name"`
	Event          string    `json:"event"`
	Source         string    `json:"source"`
	DryRun         bool      `json:"dry_run"`
	StartedAt      time.Time `json:"started_at"`
	DurationMs     int       `json:"duration_ms"`
	Steps          int       `json:"steps"`
	Actions        int       `json:"actions"`
	Writes         int       `json:"writes"`
	NotifSent      int       `json:"notif_sent"`
	NotifWouldSend int       `json:"notif_would_send"`
	NotifNone      int       `json:"notif_none"`
	Errors         int       `json:"errors"`
	Outcome        string    `json:"outcome"`
}

func (q *Queries) InsertWorkflowRun(ctx context.Context, arg InsertWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowRun,
		arg.RunID,
		arg.TicketID,
		arg.BoardID,
		arg.WorkflowID,
		arg.WorkflowName,
		arg.Event,
		arg.Source,
		arg.DryRun,
		arg.StartedAt,
		arg.DurationMs,
		arg.Steps,
		arg.Actions,
		arg.Writes,
		arg.NotifSent,
		arg.NotifWouldSend,
		arg.NotifNone,
		arg.Errors,
		arg.Outcome,
	)
	return err
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT run_id, ticket_id, board_id, workflow_id, workflow_name, event, source, dry_run, started_at, duration_ms, steps, actions, writes, notif_sent, notif_would_send, notif_none, errors, outcome FROM workflow_run
WHERE ($1::int IS NULL OR board_id = $1::int)
  AND ($2::text IS NULL OR outcome = $2::text)
  AND ($3::int IS NULL OR ticket_id = $3::int)
  AND ($4::timestamptz IS NULL OR started_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR started_at < $5::timestamptz)
  AND ($6::timestamptz IS NULL OR started_at < $6::timestamptz)
ORDER BY started_at DESC, run_id DESC
LIMIT $7
`

type ListWorkflowRunsParams struct {
	BoardID  *int       `json:"board_id"`
	Outcome  *string    `json:"outcome"`
	TicketID *int       `json:"ticket_id"`
	FromAt   *time.Time `json:"from_at"`
	ToAt     *time.Time `json:"to_at"`
	BeforeAt *time.Time `json:"before_at"`
	Lim      int32      `json:"lim"`
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]*WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns,
		arg.BoardID,
		arg.Outcome,
		arg.TicketID,
		arg.FromAt,
		arg.ToAt,
		arg.BeforeAt,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.RunID,
			&i.TicketID,
			&i.BoardID,
			&i.WorkflowID,
			&i.WorkflowName,
			&i.Event,
			&i.Source,
			&i.DryRun,
			&i.StartedAt,
			&i.DurationMs,
			&i.Steps,
			&i.Actions,
			&i.Writes,
			&i.NotifSent,
			&i.NotifWouldSend,
			&i.NotifNone,
			&i.Errors,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
